# -*- coding: utf-8 -*-
import json

from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import DataMigration
from django.db import models

from utg import templates


KEYS_MAP = {u'ACTION_BATTLEPVE1X1_ARTIFACT_BROKEN': 0,
 u'ACTION_BATTLEPVE1X1_BATTLE_STUN': 1,
 u'ACTION_BATTLEPVE1X1_DESCRIPTION': 2,
 u'ACTION_BATTLEPVE1X1_DIARY_HERO_KILLED': 3,
 u'ACTION_BATTLEPVE1X1_EXP_FOR_KILL': 4,
 u'ACTION_BATTLEPVE1X1_JOURNAL_HERO_KILLED': 5,
 u'ACTION_BATTLEPVE1X1_KILL_BEFORE_START': 6,
 u'ACTION_BATTLEPVE1X1_LEAVE_BATTLE_IN_FEAR': 7,
 u'ACTION_BATTLEPVE1X1_MOB_KILLED': 8,
 u'ACTION_BATTLEPVE1X1_NO_LOOT': 9,
 u'ACTION_BATTLEPVE1X1_PEACEFULL_BATTLE': 10,
 u'ACTION_BATTLEPVE1X1_PERIODICAL_FIRE_DAMAGE': 11,
 u'ACTION_BATTLEPVE1X1_PERIODICAL_POISON_DAMAGE': 12,
 u'ACTION_BATTLEPVE1X1_PUT_LOOT': 13,
 u'ACTION_BATTLEPVE1X1_PUT_LOOT_NO_SPACE': 14,
 u'ACTION_BATTLEPVE1X1_START': 15,
 u'ACTION_EQUIPPING_DESCRIPTION': 20000,
 u'ACTION_EQUIPPING_DIARY_CHANGE_EQUAL_ITEMS': 20001,
 u'ACTION_EQUIPPING_DIARY_CHANGE_ITEM': 20002,
 u'ACTION_EQUIPPING_DIARY_EQUIP_ITEM': 20003,
 u'ACTION_EVENT_HABIT_IN_PLACE_AGGRESSIVE_ARTIFACT': 40000,
 u'ACTION_EVENT_HABIT_IN_PLACE_AGGRESSIVE_EXPERIENCE': 40001,
 u'ACTION_EVENT_HABIT_IN_PLACE_AGGRESSIVE_MONEY': 40002,
 u'ACTION_EVENT_HABIT_IN_PLACE_AGGRESSIVE_NOTHING': 40003,
 u'ACTION_EVENT_HABIT_IN_PLACE_DISHONORABLE_ARTIFACT': 40004,
 u'ACTION_EVENT_HABIT_IN_PLACE_DISHONORABLE_EXPERIENCE': 40005,
 u'ACTION_EVENT_HABIT_IN_PLACE_DISHONORABLE_MONEY': 40006,
 u'ACTION_EVENT_HABIT_IN_PLACE_DISHONORABLE_NOTHING': 40007,
 u'ACTION_EVENT_HABIT_IN_PLACE_NOBLE_ARTIFACT': 40008,
 u'ACTION_EVENT_HABIT_IN_PLACE_NOBLE_EXPERIENCE': 40009,
 u'ACTION_EVENT_HABIT_IN_PLACE_NOBLE_MONEY': 40010,
 u'ACTION_EVENT_HABIT_IN_PLACE_NOBLE_NOTHING': 40011,
 u'ACTION_EVENT_HABIT_IN_PLACE_PEACEABLE_ARTIFACT': 40012,
 u'ACTION_EVENT_HABIT_IN_PLACE_PEACEABLE_EXPERIENCE': 40013,
 u'ACTION_EVENT_HABIT_IN_PLACE_PEACEABLE_MONEY': 40014,
 u'ACTION_EVENT_HABIT_IN_PLACE_PEACEABLE_NOTHING': 40015,
 u'ACTION_EVENT_HABIT_MOVE_TO_AGGRESSIVE_ARTIFACT': 40016,
 u'ACTION_EVENT_HABIT_MOVE_TO_AGGRESSIVE_EXPERIENCE': 40017,
 u'ACTION_EVENT_HABIT_MOVE_TO_AGGRESSIVE_MONEY': 40018,
 u'ACTION_EVENT_HABIT_MOVE_TO_AGGRESSIVE_NOTHING': 40019,
 u'ACTION_EVENT_HABIT_MOVE_TO_DISHONORABLE_ARTIFACT': 40020,
 u'ACTION_EVENT_HABIT_MOVE_TO_DISHONORABLE_EXPERIENCE': 40021,
 u'ACTION_EVENT_HABIT_MOVE_TO_DISHONORABLE_MONEY': 40022,
 u'ACTION_EVENT_HABIT_MOVE_TO_DISHONORABLE_NOTHING': 40023,
 u'ACTION_EVENT_HABIT_MOVE_TO_NOBLE_ARTIFACT': 40024,
 u'ACTION_EVENT_HABIT_MOVE_TO_NOBLE_EXPERIENCE': 40025,
 u'ACTION_EVENT_HABIT_MOVE_TO_NOBLE_MONEY': 40026,
 u'ACTION_EVENT_HABIT_MOVE_TO_NOBLE_NOTHING': 40027,
 u'ACTION_EVENT_HABIT_MOVE_TO_PEACEABLE_ARTIFACT': 40028,
 u'ACTION_EVENT_HABIT_MOVE_TO_PEACEABLE_EXPERIENCE': 40029,
 u'ACTION_EVENT_HABIT_MOVE_TO_PEACEABLE_MONEY': 40030,
 u'ACTION_EVENT_HABIT_MOVE_TO_PEACEABLE_NOTHING': 40031,
 u'ACTION_IDLENESS_DESCRIPTION': 60000,
 u'ACTION_IDLENESS_WAITING': 60001,
 u'ACTION_INPLACE_DESCRIPTION': 80000,
 u'ACTION_INPLACE_DIARY_BUYING_ARTIFACT': 80001,
 u'ACTION_INPLACE_DIARY_BUYING_ARTIFACT_AND_CHANGE': 80002,
 u'ACTION_INPLACE_DIARY_BUYING_ARTIFACT_AND_CHANGE_EQUAL_ITEMS': 80003,
 u'ACTION_INPLACE_DIARY_EXPERIENCE': 80004,
 u'ACTION_INPLACE_DIARY_IMPACT_BAD': 80005,
 u'ACTION_INPLACE_DIARY_IMPACT_GOOD': 80006,
 u'ACTION_INPLACE_DIARY_INSTANT_HEAL_FOR_MONEY': 80007,
 u'ACTION_INPLACE_DIARY_REPAIRING_ARTIFACT': 80008,
 u'ACTION_INPLACE_DIARY_SHARPENING_ARTIFACT': 80009,
 u'ACTION_INPLACE_DIARY_SPEND_USELESS': 80010,
 u'ACTION_INPLACE_HABIT_EVENT_HONOR_LEFT_1': 80011,
 u'ACTION_INPLACE_HABIT_EVENT_HONOR_LEFT_2': 80012,
 u'ACTION_INPLACE_HABIT_EVENT_HONOR_LEFT_3': 80013,
 u'ACTION_INPLACE_HABIT_EVENT_HONOR_NEUTRAL': 80014,
 u'ACTION_INPLACE_HABIT_EVENT_HONOR_RIGHT_1': 80015,
 u'ACTION_INPLACE_HABIT_EVENT_HONOR_RIGHT_2': 80016,
 u'ACTION_INPLACE_HABIT_EVENT_HONOR_RIGHT_3': 80017,
 u'ACTION_INPLACE_HABIT_EVENT_PEACEFULNESS_LEFT_1': 80018,
 u'ACTION_INPLACE_HABIT_EVENT_PEACEFULNESS_LEFT_2': 80019,
 u'ACTION_INPLACE_HABIT_EVENT_PEACEFULNESS_LEFT_3': 80020,
 u'ACTION_INPLACE_HABIT_EVENT_PEACEFULNESS_NEUTRAL': 80021,
 u'ACTION_INPLACE_HABIT_EVENT_PEACEFULNESS_RIGHT_1': 80022,
 u'ACTION_INPLACE_HABIT_EVENT_PEACEFULNESS_RIGHT_2': 80023,
 u'ACTION_INPLACE_HABIT_EVENT_PEACEFULNESS_RIGHT_3': 80024,
 u'ACTION_INPLACE_INSTANT_ENERGY_REGEN': 80025,
 u'ACTION_INPLACE_INSTANT_HEAL': 80026,
 u'ACTION_INPLACE_TAX': 80027,
 u'ACTION_INPLACE_TAX_NO_MONEY': 80028,
 u'ACTION_MOVENEARPLACE_DESCRIPTION': 100000,
 u'ACTION_MOVENEARPLACE_WALK': 100001,
 u'ACTION_MOVETO_DESCRIPTION': 120000,
 u'ACTION_MOVETO_MOVE': 120001,
 u'ACTION_MOVETO_MOVE_LONG_PATH': 120002,
 u'ACTION_MOVETO_PICKED_UP_IN_ROAD': 120003,
 u'ACTION_MOVETO_START': 120004,
 u'ACTION_QUEST_DESCRIPTION': 140000,
 u'ACTION_REGENERATE_ENERGY_DESCRIPTION_INCENSE': 160000,
 u'ACTION_REGENERATE_ENERGY_DESCRIPTION_MEDITATION': 160001,
 u'ACTION_REGENERATE_ENERGY_DESCRIPTION_PRAY': 160002,
 u'ACTION_REGENERATE_ENERGY_DESCRIPTION_SACRIFICE': 160003,
 u'ACTION_REGENERATE_ENERGY_DESCRIPTION_SYMBOLS': 160004,
 u'ACTION_REGENERATE_ENERGY_ENERGY_RECEIVED_INCENSE': 160005,
 u'ACTION_REGENERATE_ENERGY_ENERGY_RECEIVED_MEDITATION': 160006,
 u'ACTION_REGENERATE_ENERGY_ENERGY_RECEIVED_PRAY': 160007,
 u'ACTION_REGENERATE_ENERGY_ENERGY_RECEIVED_SACRIFICE': 160008,
 u'ACTION_REGENERATE_ENERGY_ENERGY_RECEIVED_SYMBOLS': 160009,
 u'ACTION_REGENERATE_ENERGY_NO_ENERGY_RECEIVED_INCENSE': 160010,
 u'ACTION_REGENERATE_ENERGY_NO_ENERGY_RECEIVED_MEDITATION': 160011,
 u'ACTION_REGENERATE_ENERGY_NO_ENERGY_RECEIVED_PRAY': 160012,
 u'ACTION_REGENERATE_ENERGY_NO_ENERGY_RECEIVED_SACRIFICE': 160013,
 u'ACTION_REGENERATE_ENERGY_NO_ENERGY_RECEIVED_SYMBOLS': 160014,
 u'ACTION_REGENERATE_ENERGY_START_INCENSE': 160015,
 u'ACTION_REGENERATE_ENERGY_START_MEDITATION': 160016,
 u'ACTION_REGENERATE_ENERGY_START_PRAY': 160017,
 u'ACTION_REGENERATE_ENERGY_START_SACRIFICE': 160018,
 u'ACTION_REGENERATE_ENERGY_START_SYMBOLS': 160019,
 u'ACTION_REST_DESCRIPTION': 180000,
 u'ACTION_REST_RESRING': 180001,
 u'ACTION_REST_START': 180002,
 u'ACTION_RESURRECT_DESCRIPTION': 200000,
 u'ACTION_RESURRECT_FINISH': 200001,
 u'ACTION_RESURRECT_RESURRECTING': 200002,
 u'ACTION_RESURRECT_START': 200003,
 u'ACTION_TRADING_DESCRIPTION': 220000,
 u'ACTION_TRADING_SELL_ITEM': 220001,
 u'ACTION_TRADING_START': 220002,
 u'ANGEL_ABILITY_ARENA_PVP_1X1': 240000,
 u'ANGEL_ABILITY_ARENA_PVP_1X1_LEAVE_QUEUE': 240001,
 u'ANGEL_ABILITY_BUILDING_REPAIR': 240002,
 u'ANGEL_ABILITY_BUILDING_REPAIR_CRIT': 240003,
 u'ANGEL_ABILITY_DROP_ITEM': 240004,
 u'ANGEL_ABILITY_DROP_ITEM_CRIT': 240005,
 u'ANGEL_ABILITY_EXPERIENCE': 240006,
 u'ANGEL_ABILITY_EXPERIENCE_CRIT': 240007,
 u'ANGEL_ABILITY_HEALHERO': 240008,
 u'ANGEL_ABILITY_HEALHERO_CRIT': 240009,
 u'ANGEL_ABILITY_LIGHTNING': 240010,
 u'ANGEL_ABILITY_LIGHTNING_CRIT': 240011,
 u'ANGEL_ABILITY_MONEY': 240012,
 u'ANGEL_ABILITY_MONEY_CRIT': 240013,
 u'ANGEL_ABILITY_RESURRECT': 240014,
 u'ANGEL_ABILITY_SHORTTELEPORT': 240015,
 u'ANGEL_ABILITY_SHORTTELEPORT_CRIT': 240016,
 u'ANGEL_ABILITY_STIMULATE': 240017,
 u'ANGEL_ABILITY_STOCK_UP_ENERGY': 240018,
 u'ANGEL_ABILITY_STOCK_UP_ENERGY_CRIT': 240019,
 u'CHRONICLE_BILL_DECLINE_BILL_FAILED': 260000,
 u'CHRONICLE_BILL_DECLINE_BILL_STARTED': 260001,
 u'CHRONICLE_BILL_DECLINE_BILL_SUCCESSED': 260002,
 u'CHRONICLE_BUILDING_CREATE_BILL_FAILED': 260003,
 u'CHRONICLE_BUILDING_CREATE_BILL_STARTED': 260004,
 u'CHRONICLE_BUILDING_CREATE_BILL_SUCCESSED': 260005,
 u'CHRONICLE_BUILDING_DESTROYED_BY_AMORTIZATION': 260009,
 u'CHRONICLE_BUILDING_DESTROY_BILL_FAILED': 260006,
 u'CHRONICLE_BUILDING_DESTROY_BILL_STARTED': 260007,
 u'CHRONICLE_BUILDING_DESTROY_BILL_SUCCESSED': 260008,
 u'CHRONICLE_BUILDING_RENAMING_BILL_FAILED': 260010,
 u'CHRONICLE_BUILDING_RENAMING_BILL_STARTED': 260011,
 u'CHRONICLE_BUILDING_RENAMING_BILL_SUCCESSED': 260012,
 u'CHRONICLE_PERSON_ARRIVED_TO_PLACE': 260013,
 u'CHRONICLE_PERSON_LEFT_PLACE': 260014,
 u'CHRONICLE_PERSON_REMOVE_BILL_FAILED': 260015,
 u'CHRONICLE_PERSON_REMOVE_BILL_STARTED': 260016,
 u'CHRONICLE_PERSON_REMOVE_BILL_SUCCESSED': 260017,
 u'CHRONICLE_PLACE_CHANGE_DESCRIPTION_BILL_FAILED': 260018,
 u'CHRONICLE_PLACE_CHANGE_DESCRIPTION_BILL_STARTED': 260019,
 u'CHRONICLE_PLACE_CHANGE_DESCRIPTION_BILL_SUCCESSED': 260020,
 u'CHRONICLE_PLACE_CHANGE_MODIFIER_BILL_FAILED_WITHOUT_OLD_MODIFIER': 260022,
 u'CHRONICLE_PLACE_CHANGE_MODIFIER_BILL_FAILED_WITH_OLD_MODIFIER': 260021,
 u'CHRONICLE_PLACE_CHANGE_MODIFIER_BILL_STARTED_WITHOUT_OLD_MODIFIER': 260024,
 u'CHRONICLE_PLACE_CHANGE_MODIFIER_BILL_STARTED_WITH_OLD_MODIFIER': 260023,
 u'CHRONICLE_PLACE_CHANGE_MODIFIER_BILL_SUCCESSED_WITHOUT_OLD_MODIFIER': 260026,
 u'CHRONICLE_PLACE_CHANGE_MODIFIER_BILL_SUCCESSED_WITH_OLD_MODIFIER': 260025,
 u'CHRONICLE_PLACE_CHANGE_NAME_BILL_FAILED': 260027,
 u'CHRONICLE_PLACE_CHANGE_NAME_BILL_STARTED': 260028,
 u'CHRONICLE_PLACE_CHANGE_NAME_BILL_SUCCESSED': 260029,
 u'CHRONICLE_PLACE_CHANGE_RACE': 260030,
 u'CHRONICLE_PLACE_LOSED_MODIFIER': 260031,
 u'CHRONICLE_PLACE_RESOURCE_CONVERSION_BILL_ENDED': 260032,
 u'CHRONICLE_PLACE_RESOURCE_CONVERSION_BILL_FAILED': 260033,
 u'CHRONICLE_PLACE_RESOURCE_CONVERSION_BILL_STARTED': 260034,
 u'CHRONICLE_PLACE_RESOURCE_CONVERSION_BILL_SUCCESSED': 260035,
 u'CHRONICLE_PLACE_RESOURCE_EXCHANGE_BILL_ENDED': 260036,
 u'CHRONICLE_PLACE_RESOURCE_EXCHANGE_BILL_FAILED': 260037,
 u'CHRONICLE_PLACE_RESOURCE_EXCHANGE_BILL_STARTED': 260038,
 u'CHRONICLE_PLACE_RESOURCE_EXCHANGE_BILL_SUCCESSED': 260039,
 u'HERO_ABILITY_FIREBALL': 280000,
 u'HERO_ABILITY_FIREBALL_MISS': 280001,
 u'HERO_ABILITY_FREEZING': 280002,
 u'HERO_ABILITY_HIT': 280003,
 u'HERO_ABILITY_HIT_MISS': 280004,
 u'HERO_ABILITY_LAST_CHANCE': 280005,
 u'HERO_ABILITY_MAGICMUSHROOM': 280006,
 u'HERO_ABILITY_POISON_CLOUD': 280007,
 u'HERO_ABILITY_REGENERATION': 280008,
 u'HERO_ABILITY_RUNUPPUSH': 280009,
 u'HERO_ABILITY_RUNUPPUSH_MISS': 280010,
 u'HERO_ABILITY_SIDESTEP': 280011,
 u'HERO_ABILITY_SPEEDUP': 280012,
 u'HERO_ABILITY_STRONG_HIT': 280013,
 u'HERO_ABILITY_STRONG_HIT_MISS': 280014,
 u'HERO_ABILITY_VAMPIRE_STRIKE': 280015,
 u'HERO_ABILITY_VAMPIRE_STRIKE_MISS': 280016,
 u'HERO_COMMON_DIARY_CREATE': 300000,
 u'HERO_COMMON_JOURNAL_CREATE_1': 300001,
 u'HERO_COMMON_JOURNAL_CREATE_2': 300002,
 u'HERO_COMMON_JOURNAL_CREATE_3': 300003,
 u'HERO_COMMON_JOURNAL_CREATE_4': 300004,
 u'HERO_COMMON_JOURNAL_LEVEL_UP': 300005,
 u'META_ACTION_ARENA_PVP_1X1_DESCRIPTION': 320000,
 u'META_ACTION_ARENA_PVP_1X1_DIARY_KILL': 320001,
 u'META_ACTION_ARENA_PVP_1X1_START': 320002,
 u'PVP_MISS_ABILITY': 340000,
 u'PVP_SAY': 340001,
 u'PVP_USE_ABILITY_BLOOD': 340002,
 u'PVP_USE_ABILITY_FLAME': 340003,
 u'PVP_USE_ABILITY_ICE': 340004,
 u'QUEST_CARAVAN_ACTION_ATTACK': 360000,
 u'QUEST_CARAVAN_ACTION_CHOOSE_ATTACK': 360001,
 u'QUEST_CARAVAN_ACTION_CHOOSE_DEFENCE': 360002,
 u'QUEST_CARAVAN_ACTION_DEFENCE': 360003,
 u'QUEST_CARAVAN_ACTION_FIGHT': 360004,
 u'QUEST_CARAVAN_ACTION_FINISH_ATTACK': 360005,
 u'QUEST_CARAVAN_ACTION_FINISH_DEFENCE': 360006,
 u'QUEST_CARAVAN_ACTION_FIRST_MOVING': 360007,
 u'QUEST_CARAVAN_ACTION_HIDE': 360008,
 u'QUEST_CARAVAN_ACTION_INTRO': 360009,
 u'QUEST_CARAVAN_ACTION_START_HIDE': 360010,
 u'QUEST_CARAVAN_ACTION_START_RUN': 360011,
 u'QUEST_CARAVAN_ACTOR_ANTAGONIST_POSITION': 360012,
 u'QUEST_CARAVAN_ACTOR_INITIATOR': 360013,
 u'QUEST_CARAVAN_ACTOR_RECEIVER': 360014,
 u'QUEST_CARAVAN_CHOICE_CURRENT_JUMP_ATTACK': 360015,
 u'QUEST_CARAVAN_CHOICE_CURRENT_JUMP_DEFENCE': 360016,
 u'QUEST_CARAVAN_CHOICE_VARIANT_JUMP_ATTACK': 360017,
 u'QUEST_CARAVAN_CHOICE_VARIANT_JUMP_DEFENCE': 360018,
 u'QUEST_CARAVAN_DIARY_CHOOSE_ATTACK': 360019,
 u'QUEST_CARAVAN_DIARY_CHOOSE_DEFENCE': 360020,
 u'QUEST_CARAVAN_DIARY_FINISH_ATTACK_ARTIFACT': 360021,
 u'QUEST_CARAVAN_DIARY_FINISH_ATTACK_FAILED': 360022,
 u'QUEST_CARAVAN_DIARY_FINISH_ATTACK_MONEY': 360023,
 u'QUEST_CARAVAN_DIARY_FINISH_DEFENCE_ARTIFACT': 360024,
 u'QUEST_CARAVAN_DIARY_FINISH_DEFENCE_FAILED': 360025,
 u'QUEST_CARAVAN_DIARY_FINISH_DEFENCE_MONEY': 360026,
 u'QUEST_CARAVAN_DIARY_INTRO': 360027,
 u'QUEST_CARAVAN_JOURNAL_ATTACK': 360028,
 u'QUEST_CARAVAN_JOURNAL_DEFENCE': 360029,
 u'QUEST_CARAVAN_JOURNAL_FIGHT': 360030,
 u'QUEST_CARAVAN_JOURNAL_HIDE': 360031,
 u'QUEST_CARAVAN_JOURNAL_STURT_RUN': 360032,
 u'QUEST_CARAVAN_NAME': 360033,
 u'QUEST_COLLECT_DEBT_ACTION_AFTER_FAILED_HELP': 380000,
 u'QUEST_COLLECT_DEBT_ACTION_AFTER_SUCCESSED_HELP': 380001,
 u'QUEST_COLLECT_DEBT_ACTION_ATTACK': 380002,
 u'QUEST_COLLECT_DEBT_ACTION_ATTACK_FAILED': 380003,
 u'QUEST_COLLECT_DEBT_ACTION_ATTACK_SUCCESSED': 380004,
 u'QUEST_COLLECT_DEBT_ACTION_BEFORE_HELP': 380005,
 u'QUEST_COLLECT_DEBT_ACTION_INTRO': 380006,
 u'QUEST_COLLECT_DEBT_ACTOR_INITIATOR': 380007,
 u'QUEST_COLLECT_DEBT_ACTOR_RECEIVER': 380008,
 u'QUEST_COLLECT_DEBT_CHOICE_CURRENT_ATTACK': 380009,
 u'QUEST_COLLECT_DEBT_CHOICE_CURRENT_HELP': 380010,
 u'QUEST_COLLECT_DEBT_CHOICE_VARIANT_ATTACK': 380011,
 u'QUEST_COLLECT_DEBT_CHOICE_VARIANT_HELP': 380012,
 u'QUEST_COLLECT_DEBT_DIARY_AFTER_FAILED_HELP': 380013,
 u'QUEST_COLLECT_DEBT_DIARY_ATTACK': 380014,
 u'QUEST_COLLECT_DEBT_DIARY_BEFORE_HELP': 380015,
 u'QUEST_COLLECT_DEBT_DIARY_FINISH_ATTACK_FAILED': 380016,
 u'QUEST_COLLECT_DEBT_DIARY_FINISH_ATTACK_SUCCESSED_ARTIFACT': 380017,
 u'QUEST_COLLECT_DEBT_DIARY_FINISH_ATTACK_SUCCESSED_MONEY': 380018,
 u'QUEST_COLLECT_DEBT_DIARY_FINISH_HELP_ARTIFACT': 380019,
 u'QUEST_COLLECT_DEBT_DIARY_FINISH_HELP_MONEY': 380020,
 u'QUEST_COLLECT_DEBT_DIARY_INTRO': 380021,
 u'QUEST_COLLECT_DEBT_JOURNAL_FINISH': 380022,
 u'QUEST_COLLECT_DEBT_JOURNAL_MOVE_TO_RECEIVER': 380023,
 u'QUEST_COLLECT_DEBT_NAME': 380024,
 u'QUEST_DELIVERY_ACTION_DELIVERY_RETURNED': 400000,
 u'QUEST_DELIVERY_ACTION_DELIVERY_STEALED': 400001,
 u'QUEST_DELIVERY_ACTION_INTRO': 400002,
 u'QUEST_DELIVERY_ACTION_START_DELIVERY': 400003,
 u'QUEST_DELIVERY_ACTION_START_FAKE': 400004,
 u'QUEST_DELIVERY_ACTION_START_STEAL': 400005,
 u'QUEST_DELIVERY_ACTOR_ANTAGONIST': 400006,
 u'QUEST_DELIVERY_ACTOR_INITIATOR': 400007,
 u'QUEST_DELIVERY_ACTOR_RECEIVER': 400008,
 u'QUEST_DELIVERY_CHOICE_CURRENT_DELIVERY': 400009,
 u'QUEST_DELIVERY_CHOICE_CURRENT_DUMMY_LIE': 400010,
 u'QUEST_DELIVERY_CHOICE_CURRENT_FAKE': 400011,
 u'QUEST_DELIVERY_CHOICE_CURRENT_STEAL': 400012,
 u'QUEST_DELIVERY_CHOICE_VARIANT_DELIVERY': 400013,
 u'QUEST_DELIVERY_CHOICE_VARIANT_DUMMY_LIE': 400014,
 u'QUEST_DELIVERY_CHOICE_VARIANT_FAKE': 400015,
 u'QUEST_DELIVERY_CHOICE_VARIANT_STEAL': 400016,
 u'QUEST_DELIVERY_DIARY_DELIVERY_RETURNED': 400017,
 u'QUEST_DELIVERY_DIARY_DELIVERY_STEALED': 400018,
 u'QUEST_DELIVERY_DIARY_FINISH_DELIVERY_ARTIFACT': 400019,
 u'QUEST_DELIVERY_DIARY_FINISH_DELIVERY_MONEY': 400020,
 u'QUEST_DELIVERY_DIARY_FINISH_FAKE_DELIVERY_ARTIFACT': 400021,
 u'QUEST_DELIVERY_DIARY_FINISH_FAKE_DELIVERY_MONEY': 400022,
 u'QUEST_DELIVERY_DIARY_FINISH_FIGHT_FOR_STEALED__HERO_DIED': 400023,
 u'QUEST_DELIVERY_DIARY_FINISH_STEAL_ARTIFACT': 400024,
 u'QUEST_DELIVERY_DIARY_FINISH_STEAL_MONEY': 400025,
 u'QUEST_DELIVERY_DIARY_INTRO': 400026,
 u'QUEST_DELIVERY_DIARY_START_DELIVERY': 400027,
 u'QUEST_DELIVERY_DIARY_START_FAKE': 400028,
 u'QUEST_DELIVERY_DIARY_START_STEAL': 400029,
 u'QUEST_DELIVERY_JOURNAL_DELIVERY_RETURNED': 400030,
 u'QUEST_DELIVERY_JOURNAL_DELIVERY_STEALED': 400031,
 u'QUEST_DELIVERY_JOURNAL_FIGHT_THIEF': 400032,
 u'QUEST_DELIVERY_JOURNAL_START_DELIVERY': 400033,
 u'QUEST_DELIVERY_JOURNAL_START_STEAL': 400034,
 u'QUEST_DELIVERY_NAME': 400035,
 u'QUEST_HELP_ACTION_AFTER_SUCCESSED_HELP': 420000,
 u'QUEST_HELP_ACTION_INTRO': 420001,
 u'QUEST_HELP_ACTOR_INITIATOR': 420002,
 u'QUEST_HELP_ACTOR_RECEIVER': 420003,
 u'QUEST_HELP_DIARY_FINISH_FAILED_ARTIFACT': 420004,
 u'QUEST_HELP_DIARY_FINISH_FAILED_MONEY': 420005,
 u'QUEST_HELP_DIARY_FINISH_SUCCESSED_ARTIFACT': 420006,
 u'QUEST_HELP_DIARY_FINISH_SUCCESSED_MONEY': 420007,
 u'QUEST_HELP_DIARY_INTRO': 420008,
 u'QUEST_HELP_FRIEND_ACTION_AFTER_HELP': 440000,
 u'QUEST_HELP_FRIEND_ACTION_BEFORE_HELP': 440001,
 u'QUEST_HELP_FRIEND_ACTION_INTRO': 440002,
 u'QUEST_HELP_FRIEND_ACTOR_RECEIVER': 440003,
 u'QUEST_HELP_FRIEND_DIARY_FINISH_MEETING_ARTIFACT': 440004,
 u'QUEST_HELP_FRIEND_DIARY_FINISH_MEETING_MONEY': 440005,
 u'QUEST_HELP_FRIEND_DIARY_INTRO': 440006,
 u'QUEST_HELP_FRIEND_NAME': 440007,
 u'QUEST_HELP_JOURNAL_BEFORE_HELP': 420009,
 u'QUEST_HELP_NAME': 420010,
 u'QUEST_HOMETOWN_ACTION_CHATTING': 460000,
 u'QUEST_HOMETOWN_ACTION_DRUNK_SONG': 460001,
 u'QUEST_HOMETOWN_ACTION_INTRO': 460002,
 u'QUEST_HOMETOWN_ACTION_REMEMBER_NAMES': 460003,
 u'QUEST_HOMETOWN_ACTION_SEARCH_OLD_FRIENDS': 460004,
 u'QUEST_HOMETOWN_ACTION_STAGGER_STREETS': 460005,
 u'QUEST_HOMETOWN_ACTOR_RECEIVER_POSITION': 460006,
 u'QUEST_HOMETOWN_DIARY_FINISH_ARTIFACT': 460007,
 u'QUEST_HOMETOWN_DIARY_FINISH_MONEY': 460008,
 u'QUEST_HOMETOWN_DIARY_INTRO': 460009,
 u'QUEST_HOMETOWN_JOURNAL_CHATTING_DESCRIPTION': 460010,
 u'QUEST_HOMETOWN_JOURNAL_CHATTING_DONOTHING': 460011,
 u'QUEST_HOMETOWN_JOURNAL_CHATTING_START': 460012,
 u'QUEST_HOMETOWN_JOURNAL_DRUNK_SONG_DESCRIPTION': 460013,
 u'QUEST_HOMETOWN_JOURNAL_DRUNK_SONG_DONOTHING': 460014,
 u'QUEST_HOMETOWN_JOURNAL_DRUNK_SONG_START': 460015,
 u'QUEST_HOMETOWN_JOURNAL_REMEMBER_NAMES_DESCRIPTION': 460016,
 u'QUEST_HOMETOWN_JOURNAL_REMEMBER_NAMES_DONOTHING': 460017,
 u'QUEST_HOMETOWN_JOURNAL_REMEMBER_NAMES_START': 460018,
 u'QUEST_HOMETOWN_JOURNAL_SEARCH_OLD_FRIENDS_DESCRIPTION': 460019,
 u'QUEST_HOMETOWN_JOURNAL_SEARCH_OLD_FRIENDS_DONOTHING': 460020,
 u'QUEST_HOMETOWN_JOURNAL_SEARCH_OLD_FRIENDS_START': 460021,
 u'QUEST_HOMETOWN_JOURNAL_STAGGER_STREETS_DESCRIPTION': 460022,
 u'QUEST_HOMETOWN_JOURNAL_STAGGER_STREETS_DONOTHING': 460023,
 u'QUEST_HOMETOWN_JOURNAL_STAGGER_STREETS_START': 460024,
 u'QUEST_HOMETOWN_NAME': 460025,
 u'QUEST_HUNT_ACTION_FIGHT': 480000,
 u'QUEST_HUNT_ACTION_INTRO': 480001,
 u'QUEST_HUNT_ACTION_MOVE_TO_HUNT': 480002,
 u'QUEST_HUNT_ACTION_RETURN_WITH_PREY': 480003,
 u'QUEST_HUNT_ACTION_START_TRACK': 480004,
 u'QUEST_HUNT_ACTOR_RECEIVER_POSITION': 480005,
 u'QUEST_HUNT_DIARY_INTRO': 480006,
 u'QUEST_HUNT_DIARY_SELL_PREY_ARTIFACT': 480007,
 u'QUEST_HUNT_DIARY_SELL_PREY_MONEY': 480008,
 u'QUEST_HUNT_JOURNAL_MOVE_TO_HUNT': 480009,
 u'QUEST_HUNT_JOURNAL_RETURN_WITH_PREY': 480010,
 u'QUEST_HUNT_JOURNAL_START_TRACK': 480011,
 u'QUEST_HUNT_NAME': 480012,
 u'QUEST_INTERFERE_ENEMY_ACTION_AFTER_INTERFERE': 500000,
 u'QUEST_INTERFERE_ENEMY_ACTION_INTRO': 500001,
 u'QUEST_INTERFERE_ENEMY_ACTOR_ANTAGONIST_POSITION': 500002,
 u'QUEST_INTERFERE_ENEMY_ACTOR_RECEIVER': 500003,
 u'QUEST_INTERFERE_ENEMY_DIARY_FINISH_ARTIFACT': 500004,
 u'QUEST_INTERFERE_ENEMY_DIARY_FINISH_MONEY': 500005,
 u'QUEST_INTERFERE_ENEMY_DIARY_INTRO': 500006,
 u'QUEST_INTERFERE_ENEMY_NAME': 500007,
 u'QUEST_PILGRIMAGE_ACTION_INTRO': 520000,
 u'QUEST_PILGRIMAGE_ACTION_SPEAK_WITH_GURU': 520001,
 u'QUEST_PILGRIMAGE_ACTION_STAGGER_HOLY_STREETS': 520002,
 u'QUEST_PILGRIMAGE_ACTOR_RECEIVER_POSITION': 520003,
 u'QUEST_PILGRIMAGE_DIARY_FINISH_ARTIFACT': 520004,
 u'QUEST_PILGRIMAGE_DIARY_FINISH_MONEY': 520005,
 u'QUEST_PILGRIMAGE_DIARY_INTRO': 520006,
 u'QUEST_PILGRIMAGE_JOURNAL_SPEAK_WITH_GURU_DESCRIPTION': 520007,
 u'QUEST_PILGRIMAGE_JOURNAL_SPEAK_WITH_GURU_DONOTHING': 520008,
 u'QUEST_PILGRIMAGE_JOURNAL_SPEAK_WITH_GURU_START': 520009,
 u'QUEST_PILGRIMAGE_JOURNAL_STAGGER_HOLY_STREETS_DESCRIPTION': 520010,
 u'QUEST_PILGRIMAGE_JOURNAL_STAGGER_HOLY_STREETS_DONOTHING': 520011,
 u'QUEST_PILGRIMAGE_JOURNAL_STAGGER_HOLY_STREETS_START': 520012,
 u'QUEST_PILGRIMAGE_NAME': 520013,
 u'QUEST_SEARCH_SMITH_ACTION_INTRO': 540000,
 u'QUEST_SEARCH_SMITH_ACTOR_RECEIVER': 540001,
 u'QUEST_SEARCH_SMITH_DIARY_INTRO': 540002,
 u'QUEST_SEARCH_SMITH_DIARY_QUEST_FAILED': 540003,
 u'QUEST_SEARCH_SMITH_DIARY_QUEST_SUCCESSED': 540004,
 u'QUEST_SEARCH_SMITH_DIARY_START_QUEST': 540005,
 u'QUEST_SEARCH_SMITH_DIARY_UPGRADE_FREE__BUY': 540011,
 u'QUEST_SEARCH_SMITH_DIARY_UPGRADE_FREE__BUY_AND_CHANGE': 540012,
 u'QUEST_SEARCH_SMITH_DIARY_UPGRADE_FREE__FAIL': 540013,
 u'QUEST_SEARCH_SMITH_DIARY_UPGRADE_FREE__REPAIR': 540014,
 u'QUEST_SEARCH_SMITH_DIARY_UPGRADE_FREE__SHARP': 540015,
 u'QUEST_SEARCH_SMITH_DIARY_UPGRADE__BUY': 540006,
 u'QUEST_SEARCH_SMITH_DIARY_UPGRADE__BUY_AND_CHANGE': 540007,
 u'QUEST_SEARCH_SMITH_DIARY_UPGRADE__FAIL': 540008,
 u'QUEST_SEARCH_SMITH_DIARY_UPGRADE__REPAIR': 540009,
 u'QUEST_SEARCH_SMITH_DIARY_UPGRADE__SHARP': 540010,
 u'QUEST_SEARCH_SMITH_NAME': 540016,
 u'QUEST_SPYING_ACTION_ARRIVED_TO_TARGET': 560000,
 u'QUEST_SPYING_ACTION_GO_BLACKMAIL': 560001,
 u'QUEST_SPYING_ACTION_GO_REPORT_DATA': 560002,
 u'QUEST_SPYING_ACTION_INTRO': 560003,
 u'QUEST_SPYING_ACTION_MOVE_TO_REPORT_DATA': 560004,
 u'QUEST_SPYING_ACTION_MOVE_TO_REPORT_LIE': 560005,
 u'QUEST_SPYING_ACTION_OPEN_UP': 560006,
 u'QUEST_SPYING_ACTION_START_OPEN_UP': 560007,
 u'QUEST_SPYING_ACTION_START_SPYING': 560008,
 u'QUEST_SPYING_ACTION_WITNESS': 560009,
 u'QUEST_SPYING_ACTION_WITNESS_FIGHT': 560010,
 u'QUEST_SPYING_ACTOR_INITIATOR': 560011,
 u'QUEST_SPYING_ACTOR_RECEIVER': 560012,
 u'QUEST_SPYING_CHOICE_CURRENT_BLACKMAIL': 560013,
 u'QUEST_SPYING_CHOICE_CURRENT_OPEN_UP': 560014,
 u'QUEST_SPYING_CHOICE_CURRENT_SPY': 560015,
 u'QUEST_SPYING_CHOICE_VARIANT_BLACKMAIL': 560016,
 u'QUEST_SPYING_CHOICE_VARIANT_OPEN_UP': 560017,
 u'QUEST_SPYING_CHOICE_VARIANT_SPY': 560018,
 u'QUEST_SPYING_DIARY_BLACKMAIL': 560019,
 u'QUEST_SPYING_DIARY_BLACKMAIL_FINISH_ARTIFACT': 560020,
 u'QUEST_SPYING_DIARY_BLACKMAIL_FINISH_MONEY': 560021,
 u'QUEST_SPYING_DIARY_INTRO': 560022,
 u'QUEST_SPYING_DIARY_MOVE_TO_REPORT_LIE': 560023,
 u'QUEST_SPYING_DIARY_OPEN_UP': 560024,
 u'QUEST_SPYING_DIARY_OPEN_UP_FINISH_ARTIFACT': 560025,
 u'QUEST_SPYING_DIARY_OPEN_UP_FINISH_MONEY': 560026,
 u'QUEST_SPYING_DIARY_OPEN_UP_LYING_ARTIFACT': 560027,
 u'QUEST_SPYING_DIARY_OPEN_UP_LYING_MONEY': 560028,
 u'QUEST_SPYING_DIARY_REPORT_DATA_ARTIFACT': 560029,
 u'QUEST_SPYING_DIARY_REPORT_DATA_MONEY': 560030,
 u'QUEST_SPYING_DIARY_SUCCESS_SPYING': 560031,
 u'QUEST_SPYING_DIARY_WITNESS': 560032,
 u'QUEST_SPYING_DIARY_WITNESS_FAILED': 560033,
 u'QUEST_SPYING_JOURNAL_ARRIVED_TO_TARGET': 560034,
 u'QUEST_SPYING_JOURNAL_WITNESS_FIGHT': 560035,
 u'QUEST_SPYING_NAME': 560036}

class Migration(DataMigration):

    def forwards(self, orm):
        for phrase_candidate in orm['phrase_candidates.PhraseCandidate'].objects.filter(state__in=(0, 2)).all():

            template = templates.Template()
            template.parse(phrase_candidate.text, externals={})

            orm['linguistics.Template'].objects.create(raw_template=phrase_candidate.text,
                                                       state=0,
                                                       author=phrase_candidate.author,
                                                       key=KEYS_MAP[phrase_candidate.subtype.upper()],
                                                       errors_status=1,
                                                       data=json.dumps({'verificators': [],
                                                                        'template': template.serialize(),
                                                                        'groups': {}}))

    def backwards(self, orm):
        orm['linguistics.Template'].objects.filter(state=0).delete()


    models = {
        u'accounts.account': {
            'Meta': {'ordering': "['nick']", 'object_name': 'Account'},
            'action_id': ('django.db.models.fields.CharField', [], {'default': 'None', 'max_length': '128', 'null': 'True', 'db_index': 'True', 'blank': 'True'}),
            'active_end_at': ('django.db.models.fields.DateTimeField', [], {'db_index': 'True'}),
            'ban_forum_end_at': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(1970, 1, 1, 0, 0)', 'db_index': 'True'}),
            'ban_game_end_at': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(1970, 1, 1, 0, 0)', 'db_index': 'True'}),
            'clan': ('django.db.models.fields.related.ForeignKey', [], {'default': 'None', 'related_name': "'+'", 'null': 'True', 'on_delete': 'models.SET_NULL', 'to': u"orm['clans.Clan']"}),
            'created_at': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(1970, 1, 1, 0, 0)', 'auto_now_add': 'True', 'db_index': 'True', 'blank': 'True'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '254', 'unique': 'True', 'null': 'True', 'blank': 'True'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "u'user_set'", 'blank': 'True', 'to': u"orm['auth.Group']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_bot': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_fast': ('django.db.models.fields.BooleanField', [], {'default': 'True', 'db_index': 'True'}),
            'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'last_news_remind_time': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(1970, 1, 1, 0, 0)', 'auto_now_add': 'True', 'blank': 'True'}),
            'might': ('django.db.models.fields.FloatField', [], {'default': '0.0'}),
            'new_messages_number': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'nick': ('django.db.models.fields.CharField', [], {'default': "u''", 'unique': 'True', 'max_length': '128', 'db_index': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'permanent_purchases': ('django.db.models.fields.TextField', [], {'default': "'[]'"}),
            'personal_messages_subscription': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'premium_end_at': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(1970, 1, 1, 0, 0)', 'db_index': 'True'}),
            'premium_expired_notification_send_at': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(1970, 1, 1, 0, 0)', 'db_index': 'True'}),
            'referer': ('django.db.models.fields.CharField', [], {'default': 'None', 'max_length': '4096', 'null': 'True'}),
            'referer_domain': ('django.db.models.fields.CharField', [], {'default': 'None', 'max_length': '256', 'null': 'True', 'db_index': 'True'}),
            'referral_of': ('django.db.models.fields.related.ForeignKey', [], {'default': 'None', 'to': u"orm['accounts.Account']", 'null': 'True', 'on_delete': 'models.SET_NULL', 'blank': 'True'}),
            'referrals_number': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'updated_at': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(1970, 1, 1, 0, 0)', 'auto_now': 'True', 'db_index': 'True', 'blank': 'True'}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "u'user_set'", 'blank': 'True', 'to': u"orm['auth.Permission']"})
        },
        u'auth.group': {
            'Meta': {'object_name': 'Group'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        u'auth.permission': {
            'Meta': {'ordering': "(u'content_type__app_label', u'content_type__model', u'codename')", 'unique_together': "((u'content_type', u'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['contenttypes.ContentType']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        u'clans.clan': {
            'Meta': {'object_name': 'Clan'},
            'abbr': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '5'}),
            'created_at': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'db_index': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.TextField', [], {'max_length': '2024'}),
            'forum_subcategory': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['forum.SubCategory']", 'on_delete': 'models.PROTECT'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'members_number': ('django.db.models.fields.IntegerField', [], {}),
            'motto': ('django.db.models.fields.CharField', [], {'max_length': '256'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '128'}),
            'updated_at': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'db_index': 'True', 'blank': 'True'})
        },
        u'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        u'forum.category': {
            'Meta': {'object_name': 'Category'},
            'caption': ('django.db.models.fields.CharField', [], {'max_length': '256'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'order': ('django.db.models.fields.IntegerField', [], {'default': '0', 'blank': 'True'}),
            'slug': ('django.db.models.fields.CharField', [], {'max_length': '32', 'db_index': 'True'})
        },
        u'forum.subcategory': {
            'Meta': {'object_name': 'SubCategory'},
            'caption': ('django.db.models.fields.CharField', [], {'max_length': '256'}),
            'category': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['forum.Category']", 'on_delete': 'models.PROTECT'}),
            'closed': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'created_at': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(1970, 1, 1, 0, 0)', 'auto_now_add': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.TextField', [], {'default': "u''"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'last_poster': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'+'", 'null': 'True', 'on_delete': 'models.SET_NULL', 'to': u"orm['accounts.Account']"}),
            'last_thread': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'+'", 'null': 'True', 'on_delete': 'models.SET_NULL', 'to': u"orm['forum.Thread']"}),
            'last_thread_created_at': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(1970, 1, 1, 0, 0)', 'auto_now_add': 'True', 'blank': 'True'}),
            'order': ('django.db.models.fields.IntegerField', [], {'default': '0', 'blank': 'True'}),
            'posts_count': ('django.db.models.fields.BigIntegerField', [], {'default': '0'}),
            'restricted': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'db_index': 'True'}),
            'threads_count': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'uid': ('django.db.models.fields.CharField', [], {'default': 'None', 'max_length': '16', 'null': 'True', 'db_index': 'True', 'blank': 'True'}),
            'updated_at': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(1970, 1, 1, 0, 0)', 'auto_now_add': 'True', 'blank': 'True'})
        },
        u'forum.thread': {
            'Meta': {'object_name': 'Thread'},
            'author': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'+'", 'null': 'True', 'on_delete': 'models.SET_NULL', 'to': u"orm['accounts.Account']"}),
            'caption': ('django.db.models.fields.CharField', [], {'max_length': '256'}),
            'created_at': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(1970, 1, 1, 0, 0)', 'auto_now_add': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'important': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'db_index': 'True'}),
            'last_poster': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'+'", 'null': 'True', 'on_delete': 'models.SET_NULL', 'to': u"orm['accounts.Account']"}),
            'posts_count': ('django.db.models.fields.BigIntegerField', [], {'default': '0'}),
            'subcategory': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['forum.SubCategory']", 'on_delete': 'models.PROTECT'}),
            'technical': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'updated_at': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(1970, 1, 1, 0, 0)', 'auto_now_add': 'True', 'blank': 'True'})
        },
        u'linguistics.contribution': {
            'Meta': {'unique_together': "(('type', 'account', 'entity_id'),)", 'object_name': 'Contribution'},
            'account': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['accounts.Account']"}),
            'created_at': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'entity_id': ('django.db.models.fields.BigIntegerField', [], {'db_index': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'type': ('rels.django.RelationIntegerField', [], {'default': '0', 'db_index': 'True'})
        },
        u'linguistics.template': {
            'Meta': {'object_name': 'Template'},
            'author': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['accounts.Account']", 'null': 'True', 'on_delete': 'models.SET_NULL'}),
            'created_at': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'data': ('django.db.models.fields.TextField', [], {}),
            'errors_status': ('rels.django.RelationIntegerField', [], {'default': '0', 'db_index': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'key': ('rels.django.RelationIntegerField', [], {'db_index': 'True'}),
            'parent': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['linguistics.Template']", 'unique': 'True', 'null': 'True', 'on_delete': 'models.SET_NULL'}),
            'raw_template': ('django.db.models.fields.TextField', [], {}),
            'state': ('rels.django.RelationIntegerField', [], {'db_index': 'True'}),
            'updated_at': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'})
        },
        u'linguistics.word': {
            'Meta': {'unique_together': "(('normal_form', 'type', 'state'),)", 'object_name': 'Word'},
            'author': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['accounts.Account']", 'null': 'True', 'on_delete': 'models.SET_NULL'}),
            'created_at': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'forms': ('django.db.models.fields.TextField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'normal_form': ('django.db.models.fields.CharField', [], {'max_length': '64'}),
            'parent': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['linguistics.Word']", 'unique': 'True', 'null': 'True', 'on_delete': 'models.SET_NULL'}),
            'state': ('rels.django.RelationIntegerField', [], {'db_index': 'True'}),
            'type': ('rels.django.RelationIntegerField', [], {'db_index': 'True'}),
            'updated_at': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'used_in_ingame_templates': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'used_in_onreview_templates': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'used_in_status': ('rels.django.RelationIntegerField', [], {'default': '2', 'db_index': 'True'})
        },
        u'phrase_candidates.phrasecandidate': {
            'Meta': {'object_name': 'PhraseCandidate'},
            'author': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'+'", 'to': u"orm['accounts.Account']"}),
            'created_at': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'moderator': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'+'", 'null': 'True', 'on_delete': 'models.SET_NULL', 'to': u"orm['accounts.Account']"}),
            'state': ('rels.django.RelationIntegerField', [], {'db_index': 'True'}),
            'subtype': ('django.db.models.fields.CharField', [], {'default': "u''", 'max_length': '256'}),
            'subtype_name': ('django.db.models.fields.CharField', [], {'default': "u''", 'max_length': '256'}),
            'text': ('django.db.models.fields.TextField', [], {'max_length': '10240', 'blank': 'True'}),
            'type': ('django.db.models.fields.CharField', [], {'max_length': '256'}),
            'type_name': ('django.db.models.fields.CharField', [], {'default': "u''", 'max_length': '256'}),
            'updated_at': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'})
        }
    }

    complete_apps = ['phrase_candidates', 'linguistics']
    symmetrical = True
