# Generated by Django 2.1.15 on 2019-12-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsolla', '0002_auto_20150506_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='test',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
