# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-26 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('matchmaker_type', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'battles',
            },
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('participant', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(db_column='battle', on_delete=django.db.models.deletion.CASCADE, to='tt_matchmaker.Battle')),
            ],
            options={
                'db_table': 'battles_participants',
            },
        ),
        migrations.CreateModel(
            name='BattleRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('initiator', models.BigIntegerField()),
                ('matchmaker_type', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'battle_requests',
            },
        ),
        migrations.AlterUniqueTogether(
            name='battlerequest',
            unique_together=set([('matchmaker_type', 'initiator')]),
        ),
    ]
