# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_actual_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='actual_bills',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='account',
            name='permanent_purchases',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='changecredentialstask',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
