# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20161019_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='new_messages_number',
        ),
    ]
