# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-11 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_middle_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changecredentialstask',
            name='relogin_required',
        ),
    ]
