# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-05 19:59
from __future__ import unicode_literals

from django.db import migrations
import rels.django


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_changecredentialstask_relogin_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cards_receive_mode',
            field=rels.django.RelationIntegerField(default=1),
        ),
    ]
