# Generated by Django 2.1.15 on 2019-12-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_cards_receive_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='news_subscription',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='personal_messages_subscription',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
