# Generated by Django 2.2.10 on 2020-03-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20191204_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomPremiumRequest',
        ),
    ]
