# Generated by Django 3.0.7 on 2020-06-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_account_removed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='actual_bills',
        ),
    ]
