- name: "preinstall datadog"
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: configure database user
      postgresql_user:
        db: postgres
        name: datadog
        password: datadog
        priv: pg_stat_database:SELECT
        role_attr_flags: "NOSUPERUSER,NOCREATEROLE,NOINHERIT,LOGIN,NOREPLICATION,NOCREATEDB"
        login_user: postgres

    - name: Allow 'dd-agent' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: 'dd-agent'
        line: 'dd-agent ALL=(root) NOPASSWD: /usr/bin/find'


- hosts: all
  become: yes
  become_user: root

  roles:
    - Datadog.datadog

  vars:
    datadog_api_key: "{{tt_datadog_api_key}}"

    datadog_config:
      use_curl_http_client: 'yes'

    datadog_checks:
      nginx:
        init_config:
        instances:
          - nginx_status_url: http://localhost/nginx-status/

      redisdb:
        init_config:
        instances:
          - host: localhost
            port: 6379
            password:

      postgres:
        init_config:
        instances:
          - host: localhost
            port: 5432
            username: datadog
            password: datadog

      postfix:
        init_config:
        instances:
          - directory: /var/spool/postfix
            queues:
              - incoming
              - active
              - deferred

      rabbitmq:
        init_config:
        instances:
          - rabbitmq_api_url: http://localhost:15672/api/
            rabbitmq_user: the_tale
            rabbitmq_pass: the_tale
