# Generated by Django 2.2.10 on 2020-03-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockrequest',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
