# Generated by Django 3.1.13 on 2021-11-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0002_auto_20200313_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockrequest',
            name='data',
            field=models.JSONField(),
        ),
    ]
