# Generated by Django 3.0.11 on 2020-11-14 12:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_infos',
            },
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('xsolla_id', models.BigIntegerField(unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'cancellations',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('expire_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(db_column='account', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tt_xsolla.AccountInfo')),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('xsolla_id', models.BigIntegerField(null=True, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_test', models.BooleanField()),
                ('is_fake', models.BooleanField()),
                ('processed_at', models.DateTimeField(db_index=True, default=None, null=True)),
                ('account', models.ForeignKey(db_column='account', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tt_xsolla.AccountInfo')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
    ]
