# Generated by Django 3.0.11 on 2020-11-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_xsolla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='state',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
