# Generated by Django 3.0.11 on 2020-11-17 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt_xsolla', '0002_accountinfo_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='account',
            field=models.ForeignKey(db_column='account', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tt_xsolla.AccountInfo'),
            preserve_default=False,
        ),
    ]
