# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-14 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_bank', '0002_auto_20171214_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('account', 'currency')]),
        ),
    ]
