# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-19 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_bank', '0003_auto_20171214_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='account',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='transaction',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.IntegerField(db_index=True),
        ),
    ]
