# Generated by Django 3.1.13 on 2021-11-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_bank', '0007_auto_20211018_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
