# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='base.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nbase.proto\x1a\x19google/protobuf/any.proto\"P\n\x08\x41piError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12%\n\x07\x64\x65tails\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\"\xb5\x01\n\x0b\x41piResponse\x12#\n\x06status\x18\x01 \x01(\x0e\x32\x13.ApiResponse.Status\x12\x13\n\x0bserver_time\x18\x02 \x01(\x01\x12$\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x12\x1a\n\x05\x65rror\x18\x04 \x01(\x0b\x32\t.ApiErrorH\x00\" \n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x42\x08\n\x06\x61nswerb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_APIRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='ApiResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=263,
  serialized_end=295,
)
_sym_db.RegisterEnumDescriptor(_APIRESPONSE_STATUS)


_APIERROR = _descriptor.Descriptor(
  name='ApiError',
  full_name='ApiError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='ApiError.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='ApiError.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='details', full_name='ApiError.details', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=121,
)


_APIRESPONSE = _descriptor.Descriptor(
  name='ApiResponse',
  full_name='ApiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ApiResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_time', full_name='ApiResponse.server_time', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='ApiResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='ApiResponse.error', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _APIRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='answer', full_name='ApiResponse.answer',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=124,
  serialized_end=305,
)

_APIERROR.fields_by_name['details'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_APIRESPONSE.fields_by_name['status'].enum_type = _APIRESPONSE_STATUS
_APIRESPONSE.fields_by_name['data'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_APIRESPONSE.fields_by_name['error'].message_type = _APIERROR
_APIRESPONSE_STATUS.containing_type = _APIRESPONSE
_APIRESPONSE.oneofs_by_name['answer'].fields.append(
  _APIRESPONSE.fields_by_name['data'])
_APIRESPONSE.fields_by_name['data'].containing_oneof = _APIRESPONSE.oneofs_by_name['answer']
_APIRESPONSE.oneofs_by_name['answer'].fields.append(
  _APIRESPONSE.fields_by_name['error'])
_APIRESPONSE.fields_by_name['error'].containing_oneof = _APIRESPONSE.oneofs_by_name['answer']
DESCRIPTOR.message_types_by_name['ApiError'] = _APIERROR
DESCRIPTOR.message_types_by_name['ApiResponse'] = _APIRESPONSE

ApiError = _reflection.GeneratedProtocolMessageType('ApiError', (_message.Message,), dict(
  DESCRIPTOR = _APIERROR,
  __module__ = 'base_pb2'
  # @@protoc_insertion_point(class_scope:ApiError)
  ))
_sym_db.RegisterMessage(ApiError)

ApiResponse = _reflection.GeneratedProtocolMessageType('ApiResponse', (_message.Message,), dict(
  DESCRIPTOR = _APIRESPONSE,
  __module__ = 'base_pb2'
  # @@protoc_insertion_point(class_scope:ApiResponse)
  ))
_sym_db.RegisterMessage(ApiResponse)


# @@protoc_insertion_point(module_scope)
