# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_protector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_protector.proto',
  package='data_protector',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x64\x61ta_protector.proto\x12\x0e\x64\x61ta_protector\"N\n\x06Report\x12\r\n\x05state\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x14\n\x0c\x63ompleted_at\x18\x03 \x01(\x01\x12\x11\n\texpire_at\x18\x04 \x01(\x01\"(\n\nSourceInfo\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"?\n\x14RequestReportRequest\x12\'\n\x03ids\x18\x01 \x03(\x0b\x32\x1a.data_protector.SourceInfo\"*\n\x15RequestReportResponse\x12\x11\n\treport_id\x18\x01 \x01(\t\"%\n\x10GetReportRequest\x12\x11\n\treport_id\x18\x01 \x01(\t\";\n\x11GetReportResponse\x12&\n\x06report\x18\x01 \x01(\x0b\x32\x16.data_protector.Report\"R\n\x16RequestDeletionRequest\x12\x0f\n\x07\x63ore_id\x18\x01 \x01(\t\x12\'\n\x03ids\x18\x02 \x03(\x0b\x32\x1a.data_protector.SourceInfo\"\x19\n\x17RequestDeletionResponse\"9\n\x13PluginReportRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06secret\x18\x02 \x01(\t\"\x8c\x01\n\x14PluginReportResponse\x12?\n\x06result\x18\x01 \x01(\x0e\x32/.data_protector.PluginReportResponse.ResultType\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"%\n\nResultType\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\";\n\x15PluginDeletionRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06secret\x18\x02 \x01(\t\"\x82\x01\n\x16PluginDeletionResponse\x12\x41\n\x06result\x18\x01 \x01(\x0e\x32\x31.data_protector.PluginDeletionResponse.ResultType\"%\n\nResultType\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\"\x1a\n\x18\x44\x65\x62ugClearServiceRequest\"\x1b\n\x19\x44\x65\x62ugClearServiceResponseb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PLUGINREPORTRESPONSE_RESULTTYPE = _descriptor.EnumDescriptor(
  name='ResultType',
  full_name='data_protector.PluginReportResponse.ResultType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=645,
  serialized_end=682,
)
_sym_db.RegisterEnumDescriptor(_PLUGINREPORTRESPONSE_RESULTTYPE)

_PLUGINDELETIONRESPONSE_RESULTTYPE = _descriptor.EnumDescriptor(
  name='ResultType',
  full_name='data_protector.PluginDeletionResponse.ResultType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=645,
  serialized_end=682,
)
_sym_db.RegisterEnumDescriptor(_PLUGINDELETIONRESPONSE_RESULTTYPE)


_REPORT = _descriptor.Descriptor(
  name='Report',
  full_name='data_protector.Report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='data_protector.Report.state', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='data_protector.Report.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='completed_at', full_name='data_protector.Report.completed_at', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expire_at', full_name='data_protector.Report.expire_at', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=118,
)


_SOURCEINFO = _descriptor.Descriptor(
  name='SourceInfo',
  full_name='data_protector.SourceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='data_protector.SourceInfo.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='data_protector.SourceInfo.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=160,
)


_REQUESTREPORTREQUEST = _descriptor.Descriptor(
  name='RequestReportRequest',
  full_name='data_protector.RequestReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='data_protector.RequestReportRequest.ids', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=225,
)


_REQUESTREPORTRESPONSE = _descriptor.Descriptor(
  name='RequestReportResponse',
  full_name='data_protector.RequestReportResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='report_id', full_name='data_protector.RequestReportResponse.report_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=269,
)


_GETREPORTREQUEST = _descriptor.Descriptor(
  name='GetReportRequest',
  full_name='data_protector.GetReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='report_id', full_name='data_protector.GetReportRequest.report_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=308,
)


_GETREPORTRESPONSE = _descriptor.Descriptor(
  name='GetReportResponse',
  full_name='data_protector.GetReportResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='report', full_name='data_protector.GetReportResponse.report', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=369,
)


_REQUESTDELETIONREQUEST = _descriptor.Descriptor(
  name='RequestDeletionRequest',
  full_name='data_protector.RequestDeletionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='core_id', full_name='data_protector.RequestDeletionRequest.core_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ids', full_name='data_protector.RequestDeletionRequest.ids', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=453,
)


_REQUESTDELETIONRESPONSE = _descriptor.Descriptor(
  name='RequestDeletionResponse',
  full_name='data_protector.RequestDeletionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=480,
)


_PLUGINREPORTREQUEST = _descriptor.Descriptor(
  name='PluginReportRequest',
  full_name='data_protector.PluginReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='data_protector.PluginReportRequest.account_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secret', full_name='data_protector.PluginReportRequest.secret', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=539,
)


_PLUGINREPORTRESPONSE = _descriptor.Descriptor(
  name='PluginReportResponse',
  full_name='data_protector.PluginReportResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='data_protector.PluginReportResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='data_protector.PluginReportResponse.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PLUGINREPORTRESPONSE_RESULTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=542,
  serialized_end=682,
)


_PLUGINDELETIONREQUEST = _descriptor.Descriptor(
  name='PluginDeletionRequest',
  full_name='data_protector.PluginDeletionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='data_protector.PluginDeletionRequest.account_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secret', full_name='data_protector.PluginDeletionRequest.secret', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=684,
  serialized_end=743,
)


_PLUGINDELETIONRESPONSE = _descriptor.Descriptor(
  name='PluginDeletionResponse',
  full_name='data_protector.PluginDeletionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='data_protector.PluginDeletionResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PLUGINDELETIONRESPONSE_RESULTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=746,
  serialized_end=876,
)


_DEBUGCLEARSERVICEREQUEST = _descriptor.Descriptor(
  name='DebugClearServiceRequest',
  full_name='data_protector.DebugClearServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=878,
  serialized_end=904,
)


_DEBUGCLEARSERVICERESPONSE = _descriptor.Descriptor(
  name='DebugClearServiceResponse',
  full_name='data_protector.DebugClearServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=906,
  serialized_end=933,
)

_REQUESTREPORTREQUEST.fields_by_name['ids'].message_type = _SOURCEINFO
_GETREPORTRESPONSE.fields_by_name['report'].message_type = _REPORT
_REQUESTDELETIONREQUEST.fields_by_name['ids'].message_type = _SOURCEINFO
_PLUGINREPORTRESPONSE.fields_by_name['result'].enum_type = _PLUGINREPORTRESPONSE_RESULTTYPE
_PLUGINREPORTRESPONSE_RESULTTYPE.containing_type = _PLUGINREPORTRESPONSE
_PLUGINDELETIONRESPONSE.fields_by_name['result'].enum_type = _PLUGINDELETIONRESPONSE_RESULTTYPE
_PLUGINDELETIONRESPONSE_RESULTTYPE.containing_type = _PLUGINDELETIONRESPONSE
DESCRIPTOR.message_types_by_name['Report'] = _REPORT
DESCRIPTOR.message_types_by_name['SourceInfo'] = _SOURCEINFO
DESCRIPTOR.message_types_by_name['RequestReportRequest'] = _REQUESTREPORTREQUEST
DESCRIPTOR.message_types_by_name['RequestReportResponse'] = _REQUESTREPORTRESPONSE
DESCRIPTOR.message_types_by_name['GetReportRequest'] = _GETREPORTREQUEST
DESCRIPTOR.message_types_by_name['GetReportResponse'] = _GETREPORTRESPONSE
DESCRIPTOR.message_types_by_name['RequestDeletionRequest'] = _REQUESTDELETIONREQUEST
DESCRIPTOR.message_types_by_name['RequestDeletionResponse'] = _REQUESTDELETIONRESPONSE
DESCRIPTOR.message_types_by_name['PluginReportRequest'] = _PLUGINREPORTREQUEST
DESCRIPTOR.message_types_by_name['PluginReportResponse'] = _PLUGINREPORTRESPONSE
DESCRIPTOR.message_types_by_name['PluginDeletionRequest'] = _PLUGINDELETIONREQUEST
DESCRIPTOR.message_types_by_name['PluginDeletionResponse'] = _PLUGINDELETIONRESPONSE
DESCRIPTOR.message_types_by_name['DebugClearServiceRequest'] = _DEBUGCLEARSERVICEREQUEST
DESCRIPTOR.message_types_by_name['DebugClearServiceResponse'] = _DEBUGCLEARSERVICERESPONSE

Report = _reflection.GeneratedProtocolMessageType('Report', (_message.Message,), dict(
  DESCRIPTOR = _REPORT,
  __module__ = 'data_protector_pb2'
  # @@protoc_insertion_point(class_scope:data_protector.Report)
  ))
_sym_db.RegisterMessage(Report)

SourceInfo = _reflection.GeneratedProtocolMessageType('SourceInfo', (_message.Message,), dict(
  DESCRIPTOR = _SOURCEINFO,
  __module__ = 'data_protector_pb2'
  # @@protoc_insertion_point(class_scope:data_protector.SourceInfo)
  ))
_sym_db.RegisterMessage(SourceInfo)

RequestReportRequest = _reflection.GeneratedProtocolMessageType('RequestReportRequest', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTREPORTREQUEST,
  __module__ = 'data_protector_pb2'
  # @@protoc_insertion_point(class_scope:data_protector.RequestReportRequest)
  ))
_sym_db.RegisterMessage(RequestReportRequest)

RequestReportResponse = _reflection.GeneratedProtocolMessageType('RequestReportResponse', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTREPORTRESPONSE,
  __module__ = 'data_protector_pb2'
  # @@protoc_insertion_point(class_scope:data_protector.RequestReportResponse)
  ))
_sym_db.RegisterMessage(RequestReportResponse)

GetReportRequest = _reflection.GeneratedProtocolMessageType('GetReportRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETREPORTREQUEST,
  __module__ = 'data_protector_pb2'
  # @@protoc_insertion_point(class_scope:data_protector.GetReportRequest)
  ))
_sym_db.RegisterMessage(GetReportRequest)

GetReportResponse = _reflection.GeneratedProtocolMessageType('GetReportResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETREPORTRESPONSE,
  __module__ = 'data_protector_pb2'
  # @@protoc_insertion_point(class_scope:data_protector.GetReportResponse)
  ))
_sym_db.RegisterMessage(GetReportResponse)

RequestDeletionRequest = _reflection.GeneratedProtocolMessageType('RequestDeletionRequest', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTDELETIONREQUEST,
  __module__ = 'data_protector_pb2'
  # @@protoc_insertion_point(class_scope:data_protector.RequestDeletionRequest)
  ))
_sym_db.RegisterMessage(RequestDeletionRequest)

RequestDeletionResponse = _reflection.GeneratedProtocolMessageType('RequestDeletionResponse', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTDELETIONRESPONSE,
  __module__ = 'data_protector_pb2'
  # @@protoc_insertion_point(class_scope:data_protector.RequestDeletionResponse)
  ))
_sym_db.RegisterMessage(RequestDeletionResponse)

PluginReportRequest = _reflection.GeneratedProtocolMessageType('PluginReportRequest', (_message.Message,), dict(
  DESCRIPTOR = _PLUGINREPORTREQUEST,
  __module__ = 'data_protector_pb2'
  # @@protoc_insertion_point(class_scope:data_protector.PluginReportRequest)
  ))
_sym_db.RegisterMessage(PluginReportRequest)

PluginReportResponse = _reflection.GeneratedProtocolMessageType('PluginReportResponse', (_message.Message,), dict(
  DESCRIPTOR = _PLUGINREPORTRESPONSE,
  __module__ = 'data_protector_pb2'
  # @@protoc_insertion_point(class_scope:data_protector.PluginReportResponse)
  ))
_sym_db.RegisterMessage(PluginReportResponse)

PluginDeletionRequest = _reflection.GeneratedProtocolMessageType('PluginDeletionRequest', (_message.Message,), dict(
  DESCRIPTOR = _PLUGINDELETIONREQUEST,
  __module__ = 'data_protector_pb2'
  # @@protoc_insertion_point(class_scope:data_protector.PluginDeletionRequest)
  ))
_sym_db.RegisterMessage(PluginDeletionRequest)

PluginDeletionResponse = _reflection.GeneratedProtocolMessageType('PluginDeletionResponse', (_message.Message,), dict(
  DESCRIPTOR = _PLUGINDELETIONRESPONSE,
  __module__ = 'data_protector_pb2'
  # @@protoc_insertion_point(class_scope:data_protector.PluginDeletionResponse)
  ))
_sym_db.RegisterMessage(PluginDeletionResponse)

DebugClearServiceRequest = _reflection.GeneratedProtocolMessageType('DebugClearServiceRequest', (_message.Message,), dict(
  DESCRIPTOR = _DEBUGCLEARSERVICEREQUEST,
  __module__ = 'data_protector_pb2'
  # @@protoc_insertion_point(class_scope:data_protector.DebugClearServiceRequest)
  ))
_sym_db.RegisterMessage(DebugClearServiceRequest)

DebugClearServiceResponse = _reflection.GeneratedProtocolMessageType('DebugClearServiceResponse', (_message.Message,), dict(
  DESCRIPTOR = _DEBUGCLEARSERVICERESPONSE,
  __module__ = 'data_protector_pb2'
  # @@protoc_insertion_point(class_scope:data_protector.DebugClearServiceResponse)
  ))
_sym_db.RegisterMessage(DebugClearServiceResponse)


# @@protoc_insertion_point(module_scope)
