# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: diary.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='diary.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x64iary.proto\"\xe6\x01\n\x07Message\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x13\n\x0bturn_number\x18\x02 \x01(\x04\x12\x0c\n\x04type\x18\x03 \x01(\r\x12\x11\n\tgame_time\x18\x04 \x01(\t\x12\x11\n\tgame_date\x18\x05 \x01(\t\x12\x10\n\x08position\x18\x06 \x01(\t\x12\x0f\n\x07message\x18\x07 \x01(\t\x12*\n\tvariables\x18\x08 \x03(\x0b\x32\x17.Message.VariablesEntry\x1a\x30\n\x0eVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"4\n\x05\x44iary\x12\x0f\n\x07version\x18\x01 \x01(\x04\x12\x1a\n\x08messages\x18\x02 \x03(\x0b\x32\x08.Message\"$\n\x0eVersionRequest\x12\x12\n\naccount_id\x18\x01 \x01(\r\"\"\n\x0fVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\x04\"W\n\x12PushMessageRequest\x12\x12\n\naccount_id\x18\x01 \x01(\r\x12\x12\n\ndiary_size\x18\x02 \x01(\r\x12\x19\n\x07message\x18\x03 \x01(\x0b\x32\x08.Message\"\x15\n\x13PushMessageResponse\"\"\n\x0c\x44iaryRequest\x12\x12\n\naccount_id\x18\x01 \x01(\r\"&\n\rDiaryResponse\x12\x15\n\x05\x64iary\x18\x01 \x01(\x0b\x32\x06.Diaryb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MESSAGE_VARIABLESENTRY = _descriptor.Descriptor(
  name='VariablesEntry',
  full_name='Message.VariablesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Message.VariablesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Message.VariablesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=246,
)

_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Message.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='turn_number', full_name='Message.turn_number', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Message.type', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_time', full_name='Message.game_time', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_date', full_name='Message.game_date', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='Message.position', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='Message.message', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='variables', full_name='Message.variables', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGE_VARIABLESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=246,
)


_DIARY = _descriptor.Descriptor(
  name='Diary',
  full_name='Diary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='Diary.version', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='messages', full_name='Diary.messages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=300,
)


_VERSIONREQUEST = _descriptor.Descriptor(
  name='VersionRequest',
  full_name='VersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='VersionRequest.account_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=338,
)


_VERSIONRESPONSE = _descriptor.Descriptor(
  name='VersionResponse',
  full_name='VersionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='VersionResponse.version', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=374,
)


_PUSHMESSAGEREQUEST = _descriptor.Descriptor(
  name='PushMessageRequest',
  full_name='PushMessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='PushMessageRequest.account_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diary_size', full_name='PushMessageRequest.diary_size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='PushMessageRequest.message', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=463,
)


_PUSHMESSAGERESPONSE = _descriptor.Descriptor(
  name='PushMessageResponse',
  full_name='PushMessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=486,
)


_DIARYREQUEST = _descriptor.Descriptor(
  name='DiaryRequest',
  full_name='DiaryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='DiaryRequest.account_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=522,
)


_DIARYRESPONSE = _descriptor.Descriptor(
  name='DiaryResponse',
  full_name='DiaryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='diary', full_name='DiaryResponse.diary', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=562,
)

_MESSAGE_VARIABLESENTRY.containing_type = _MESSAGE
_MESSAGE.fields_by_name['variables'].message_type = _MESSAGE_VARIABLESENTRY
_DIARY.fields_by_name['messages'].message_type = _MESSAGE
_PUSHMESSAGEREQUEST.fields_by_name['message'].message_type = _MESSAGE
_DIARYRESPONSE.fields_by_name['diary'].message_type = _DIARY
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Diary'] = _DIARY
DESCRIPTOR.message_types_by_name['VersionRequest'] = _VERSIONREQUEST
DESCRIPTOR.message_types_by_name['VersionResponse'] = _VERSIONRESPONSE
DESCRIPTOR.message_types_by_name['PushMessageRequest'] = _PUSHMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['PushMessageResponse'] = _PUSHMESSAGERESPONSE
DESCRIPTOR.message_types_by_name['DiaryRequest'] = _DIARYREQUEST
DESCRIPTOR.message_types_by_name['DiaryResponse'] = _DIARYRESPONSE

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(

  VariablesEntry = _reflection.GeneratedProtocolMessageType('VariablesEntry', (_message.Message,), dict(
    DESCRIPTOR = _MESSAGE_VARIABLESENTRY,
    __module__ = 'diary_pb2'
    # @@protoc_insertion_point(class_scope:Message.VariablesEntry)
    ))
  ,
  DESCRIPTOR = _MESSAGE,
  __module__ = 'diary_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  ))
_sym_db.RegisterMessage(Message)
_sym_db.RegisterMessage(Message.VariablesEntry)

Diary = _reflection.GeneratedProtocolMessageType('Diary', (_message.Message,), dict(
  DESCRIPTOR = _DIARY,
  __module__ = 'diary_pb2'
  # @@protoc_insertion_point(class_scope:Diary)
  ))
_sym_db.RegisterMessage(Diary)

VersionRequest = _reflection.GeneratedProtocolMessageType('VersionRequest', (_message.Message,), dict(
  DESCRIPTOR = _VERSIONREQUEST,
  __module__ = 'diary_pb2'
  # @@protoc_insertion_point(class_scope:VersionRequest)
  ))
_sym_db.RegisterMessage(VersionRequest)

VersionResponse = _reflection.GeneratedProtocolMessageType('VersionResponse', (_message.Message,), dict(
  DESCRIPTOR = _VERSIONRESPONSE,
  __module__ = 'diary_pb2'
  # @@protoc_insertion_point(class_scope:VersionResponse)
  ))
_sym_db.RegisterMessage(VersionResponse)

PushMessageRequest = _reflection.GeneratedProtocolMessageType('PushMessageRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUSHMESSAGEREQUEST,
  __module__ = 'diary_pb2'
  # @@protoc_insertion_point(class_scope:PushMessageRequest)
  ))
_sym_db.RegisterMessage(PushMessageRequest)

PushMessageResponse = _reflection.GeneratedProtocolMessageType('PushMessageResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUSHMESSAGERESPONSE,
  __module__ = 'diary_pb2'
  # @@protoc_insertion_point(class_scope:PushMessageResponse)
  ))
_sym_db.RegisterMessage(PushMessageResponse)

DiaryRequest = _reflection.GeneratedProtocolMessageType('DiaryRequest', (_message.Message,), dict(
  DESCRIPTOR = _DIARYREQUEST,
  __module__ = 'diary_pb2'
  # @@protoc_insertion_point(class_scope:DiaryRequest)
  ))
_sym_db.RegisterMessage(DiaryRequest)

DiaryResponse = _reflection.GeneratedProtocolMessageType('DiaryResponse', (_message.Message,), dict(
  DESCRIPTOR = _DIARYRESPONSE,
  __module__ = 'diary_pb2'
  # @@protoc_insertion_point(class_scope:DiaryResponse)
  ))
_sym_db.RegisterMessage(DiaryResponse)


_MESSAGE_VARIABLESENTRY.has_options = True
_MESSAGE_VARIABLESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
