# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: properties.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='properties.proto',
  package='properties',
  syntax='proto3',
  serialized_pb=_b('\n\x10properties.proto\x12\nproperties\"\x91\x01\n\x08Property\x12\x11\n\tobject_id\x18\x01 \x01(\x04\x12\x0c\n\x04type\x18\x02 \x01(\x04\x12\r\n\x05value\x18\x03 \x01(\t\x12\'\n\x04mode\x18\x04 \x01(\x0e\x32\x19.properties.Property.Mode\",\n\x04Mode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07REPLACE\x10\x01\x12\n\n\x06\x41PPEND\x10\x02\"2\n\x0ePropertiesList\x12\x11\n\tobject_id\x18\x01 \x01(\x04\x12\r\n\x05types\x18\x02 \x03(\x04\"@\n\x14SetPropertiesRequest\x12(\n\nproperties\x18\x01 \x03(\x0b\x32\x14.properties.Property\"\x17\n\x15SetPropertiesResponse\"C\n\x14GetPropertiesRequest\x12+\n\x07objects\x18\x01 \x03(\x0b\x32\x1a.properties.PropertiesList\"A\n\x15GetPropertiesResponse\x12(\n\nproperties\x18\x01 \x03(\x0b\x32\x14.properties.Property\"\x1a\n\x18\x44\x65\x62ugClearServiceRequest\"\x1b\n\x19\x44\x65\x62ugClearServiceResponseb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PROPERTY_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='properties.Property.Mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPLACE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APPEND', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=134,
  serialized_end=178,
)
_sym_db.RegisterEnumDescriptor(_PROPERTY_MODE)


_PROPERTY = _descriptor.Descriptor(
  name='Property',
  full_name='properties.Property',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_id', full_name='properties.Property.object_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='properties.Property.type', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='properties.Property.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode', full_name='properties.Property.mode', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROPERTY_MODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=178,
)


_PROPERTIESLIST = _descriptor.Descriptor(
  name='PropertiesList',
  full_name='properties.PropertiesList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_id', full_name='properties.PropertiesList.object_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='types', full_name='properties.PropertiesList.types', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=230,
)


_SETPROPERTIESREQUEST = _descriptor.Descriptor(
  name='SetPropertiesRequest',
  full_name='properties.SetPropertiesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='properties', full_name='properties.SetPropertiesRequest.properties', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=296,
)


_SETPROPERTIESRESPONSE = _descriptor.Descriptor(
  name='SetPropertiesResponse',
  full_name='properties.SetPropertiesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=321,
)


_GETPROPERTIESREQUEST = _descriptor.Descriptor(
  name='GetPropertiesRequest',
  full_name='properties.GetPropertiesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='objects', full_name='properties.GetPropertiesRequest.objects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=390,
)


_GETPROPERTIESRESPONSE = _descriptor.Descriptor(
  name='GetPropertiesResponse',
  full_name='properties.GetPropertiesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='properties', full_name='properties.GetPropertiesResponse.properties', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=457,
)


_DEBUGCLEARSERVICEREQUEST = _descriptor.Descriptor(
  name='DebugClearServiceRequest',
  full_name='properties.DebugClearServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=485,
)


_DEBUGCLEARSERVICERESPONSE = _descriptor.Descriptor(
  name='DebugClearServiceResponse',
  full_name='properties.DebugClearServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=514,
)

_PROPERTY.fields_by_name['mode'].enum_type = _PROPERTY_MODE
_PROPERTY_MODE.containing_type = _PROPERTY
_SETPROPERTIESREQUEST.fields_by_name['properties'].message_type = _PROPERTY
_GETPROPERTIESREQUEST.fields_by_name['objects'].message_type = _PROPERTIESLIST
_GETPROPERTIESRESPONSE.fields_by_name['properties'].message_type = _PROPERTY
DESCRIPTOR.message_types_by_name['Property'] = _PROPERTY
DESCRIPTOR.message_types_by_name['PropertiesList'] = _PROPERTIESLIST
DESCRIPTOR.message_types_by_name['SetPropertiesRequest'] = _SETPROPERTIESREQUEST
DESCRIPTOR.message_types_by_name['SetPropertiesResponse'] = _SETPROPERTIESRESPONSE
DESCRIPTOR.message_types_by_name['GetPropertiesRequest'] = _GETPROPERTIESREQUEST
DESCRIPTOR.message_types_by_name['GetPropertiesResponse'] = _GETPROPERTIESRESPONSE
DESCRIPTOR.message_types_by_name['DebugClearServiceRequest'] = _DEBUGCLEARSERVICEREQUEST
DESCRIPTOR.message_types_by_name['DebugClearServiceResponse'] = _DEBUGCLEARSERVICERESPONSE

Property = _reflection.GeneratedProtocolMessageType('Property', (_message.Message,), dict(
  DESCRIPTOR = _PROPERTY,
  __module__ = 'properties_pb2'
  # @@protoc_insertion_point(class_scope:properties.Property)
  ))
_sym_db.RegisterMessage(Property)

PropertiesList = _reflection.GeneratedProtocolMessageType('PropertiesList', (_message.Message,), dict(
  DESCRIPTOR = _PROPERTIESLIST,
  __module__ = 'properties_pb2'
  # @@protoc_insertion_point(class_scope:properties.PropertiesList)
  ))
_sym_db.RegisterMessage(PropertiesList)

SetPropertiesRequest = _reflection.GeneratedProtocolMessageType('SetPropertiesRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETPROPERTIESREQUEST,
  __module__ = 'properties_pb2'
  # @@protoc_insertion_point(class_scope:properties.SetPropertiesRequest)
  ))
_sym_db.RegisterMessage(SetPropertiesRequest)

SetPropertiesResponse = _reflection.GeneratedProtocolMessageType('SetPropertiesResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETPROPERTIESRESPONSE,
  __module__ = 'properties_pb2'
  # @@protoc_insertion_point(class_scope:properties.SetPropertiesResponse)
  ))
_sym_db.RegisterMessage(SetPropertiesResponse)

GetPropertiesRequest = _reflection.GeneratedProtocolMessageType('GetPropertiesRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPROPERTIESREQUEST,
  __module__ = 'properties_pb2'
  # @@protoc_insertion_point(class_scope:properties.GetPropertiesRequest)
  ))
_sym_db.RegisterMessage(GetPropertiesRequest)

GetPropertiesResponse = _reflection.GeneratedProtocolMessageType('GetPropertiesResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETPROPERTIESRESPONSE,
  __module__ = 'properties_pb2'
  # @@protoc_insertion_point(class_scope:properties.GetPropertiesResponse)
  ))
_sym_db.RegisterMessage(GetPropertiesResponse)

DebugClearServiceRequest = _reflection.GeneratedProtocolMessageType('DebugClearServiceRequest', (_message.Message,), dict(
  DESCRIPTOR = _DEBUGCLEARSERVICEREQUEST,
  __module__ = 'properties_pb2'
  # @@protoc_insertion_point(class_scope:properties.DebugClearServiceRequest)
  ))
_sym_db.RegisterMessage(DebugClearServiceRequest)

DebugClearServiceResponse = _reflection.GeneratedProtocolMessageType('DebugClearServiceResponse', (_message.Message,), dict(
  DESCRIPTOR = _DEBUGCLEARSERVICERESPONSE,
  __module__ = 'properties_pb2'
  # @@protoc_insertion_point(class_scope:properties.DebugClearServiceResponse)
  ))
_sym_db.RegisterMessage(DebugClearServiceResponse)


# @@protoc_insertion_point(module_scope)
