# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-11-19 17:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import rels.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0008_remove_building_integrity'),
        ('clans', '0010_fill_linguistics_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emissary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', rels.django.RelationIntegerField(db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default='{}')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clans.Clan')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='places.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', rels.django.RelationIntegerField(db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default='{}')),
                ('stop_reason', rels.django.RelationIntegerField(db_index=True)),
                ('emissary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='emissaries.Emissary')),
            ],
        ),
    ]
