# Generated by Django 2.1.15 on 2019-12-04 19:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissary',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
