# Generated by Django 3.1.13 on 2021-11-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissaries', '0002_auto_20191204_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissary',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.JSONField(),
        ),
    ]
