# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-11-03 11:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attribute', models.BigIntegerField()),
                ('entity', models.BigIntegerField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'effects',
            },
        ),
    ]
