# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-11-03 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_effects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
