# Generated by Django 3.0.11 on 2021-10-18 19:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_effects', '0002_auto_20191103_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
