# Generated by Django 3.1.13 on 2021-11-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_effects', '0003_auto_20211018_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
