# Generated by Django 2.2.10 on 2020-03-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='name',
            field=models.CharField(default='fake', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterIndexTogether(
            name='history',
            index_together={('name', 'state')},
        ),
    ]
