# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-30 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0002_auto_20150504_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='person',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='place',
        ),
        migrations.RemoveField(
            model_name='record',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='recordtoactor',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='recordtoactor',
            name='record',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='RecordToActor',
        ),
    ]
