# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 17:13
from __future__ import unicode_literals

from django.db import migrations


def remove_removed_persons(apps, schema_editor):
    apps.get_model("persons", "Person").objects.exclude(state=0).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_scale_power'),
    ]

    operations = [
        migrations.RunPython(
            remove_removed_persons,
        ),
    ]
