# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 16:58
from __future__ import unicode_literals

import json

from django.db import migrations


def add_political_power(apps, schema_editor):
    for person in apps.get_model("persons", "Person").objects.all().iterator():
        data = json.loads(person.data)

        data['politic_power'] = {'outer_power': 50000,
                                 'inner_power': 5000,
                                 'inner_circle': {}}

        person.data = json.dumps(data, ensure_ascii=True)

        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_add_personality'),
    ]

    operations = [
        migrations.RunPython(add_political_power)
    ]
