# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_auto_20160319_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 12, 19, 59, 16, 889911)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at_turn',
            field=models.BigIntegerField(default=0),
        ),
    ]
