# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 18:18
from __future__ import unicode_literals

import json

from django.db import migrations


def fix_ruittar_name(apps, schema_editor):
    for person in apps.get_model("persons", "Person").objects.all().iterator():

        data = json.loads(person.data)

        if data['name']['forms'][0] != u'Руиттар':
            continue

        data['name']['forms'] = [u'Руиттар'] * len(data['name']['forms'])

        person.data = json.dumps(data, ensure_ascii=True)

        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0012_fix_goblib_names'),
    ]

    operations = [
        migrations.RunPython(fix_ruittar_name)
    ]
