# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-29 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorImpact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_type', models.IntegerField()),
                ('actor', models.BigIntegerField()),
                ('target_type', models.IntegerField()),
                ('target', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_at_turn', models.BigIntegerField()),
            ],
            options={
                'db_table': 'actors_impacts',
            },
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_type', models.IntegerField()),
                ('actor', models.BigIntegerField()),
                ('target_type', models.IntegerField()),
                ('target', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
                ('transaction', models.UUIDField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_at_turn', models.BigIntegerField()),
            ],
            options={
                'db_table': 'impacts',
            },
        ),
        migrations.CreateModel(
            name='TargetImpact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_type', models.IntegerField()),
                ('target', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_at_turn', models.BigIntegerField()),
            ],
            options={
                'db_table': 'targets_impacts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='targetimpact',
            unique_together=set([('target_type', 'target')]),
        ),
        migrations.AlterUniqueTogether(
            name='actorimpact',
            unique_together=set([('actor_type', 'actor', 'target_type', 'target')]),
        ),
    ]
