# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-26 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_impacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='actorimpact',
            index_together=set([('target_type', 'target'), ('actor_type', 'actor')]),
        ),
        migrations.AlterIndexTogether(
            name='impact',
            index_together=set([('actor_type', 'actor', 'created_at'), ('target_type', 'target', 'created_at'), ('actor_type', 'actor', 'target_type', 'target', 'created_at')]),
        ),
    ]
