ARG TT_BASE_IMAGE_VERSION
ARG TT_CONTAINERS_REGISTRY

FROM $TT_CONTAINERS_REGISTRY/the-tale/tt-base:$TT_BASE_IMAGE_VERSION

ARG TT_PACKAGE

COPY --chown=$TT_USER ./docker/tt_service/bin/* $HOME_BIN

RUN . $TT_VENV/bin/activate && \
    cd $TT_REPOSITORY/src/$TT_PACKAGE && poetry install

ENV TT_PACKAGE="$TT_PACKAGE" \
    TT_CONFIG="$HOME/config.json"
