volumes:
  postgresql-storage: {}
  postgresql-backups: {}


services:

  core-postgresql:
    volumes:
       - postgresql-storage:/var/lib/postgresql/data

  utils-postgresql:
    volumes:
       - postgresql-backups:/backups/

  site:

    depends_on:
      - utils-site-generate-static
