services:

  core-postgresql:
    volumes:
       - type: tmpfs
         target: /var/lib/postgresql/data

  core-nginx:
    environment:
      TT_SERVERS: "site"
    volumes:
      - $TT_CONFIGS_ROOT/nginx/templates:/nginx-config-templates:ro

  core-postfix:
    entrypoint: bash -c
    command: echo "turned off"

  tt-diary:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-personal-messages:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-storage:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-market:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-players-timers:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-personal-impacts:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-crowd-impacts:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-job-impacts:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-fame-impacts:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-game-chronicle:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-clans-chronicle:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-money-spendings:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-emissaries-impacts:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-players-properties:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-clans-properties:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-matchmaker:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-places-effects:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-clans-currencies:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-emissaries-events-currencies:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-emissaries-events-uniquer:
    volumes:
      - ${PWD}:/home/tt_service/repository

  tt-data-protector:
    volumes:
      - ${PWD}:/home/tt_service/repository

  site:
    volumes:
      - ${PWD}:/home/tt_service/repository

  utils-site-migrations:
    volumes:
      - ${PWD}:/home/tt_service/repository

  utils-site:
    volumes:
      - ${PWD}:/home/tt_service/repository
