networks:
  tt_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16


volumes:
  tt_site_static: {}
  tt_certbot_well_known: {}
  tt_certbot_storage: {}


services:

  core-postgresql:
    image: $TT_CONTAINERS_REGISTRY/the-tale/core-postgresql:$TT_RELEASE_VERSION

    volumes:
       - $TT_CONFIGS_ROOT/postgresql/postgresql.$TT_ENV.conf:/etc/postgresql/postgresql.conf:ro

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $TT_DB_ROOT_PASSWORD

    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  core-redis:

    image: $TT_CONTAINERS_REGISTRY/the-tale/core-redis:$TT_RELEASE_VERSION

  core-rabbitmq:

    image: $TT_CONTAINERS_REGISTRY/the-tale/core-rabbitmq:$TT_RELEASE_VERSION

    volumes:
       - $TT_CONFIGS_ROOT/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

  core-nginx:

    image: $TT_CONTAINERS_REGISTRY/the-tale/core-nginx:$TT_RELEASE_VERSION

    stop_grace_period: 1s

    volumes:
      - $TT_CONFIGS_ROOT/nginx/config.$TT_ENV.json:/root/nginx_config.json:ro
      - tt_certbot_well_known:/var/www/certbot/:ro
      - tt_certbot_storage:/etc/letsencrypt/:ro
      - tt_site_static:/var/www/site/:ro

    ports:
      - "80:80"
      - "443:443"

  core-postfix:
    image: $TT_CONTAINERS_REGISTRY/the-tale/core-postfix:$TT_RELEASE_VERSION

    ports:
      - "25:25"

  utils-postgresql: {}

  utils-certbot: {}

  utils-regenerate-protocol:
    image: $TT_CONTAINERS_REGISTRY/the-tale/utils-regenerate-protocol:$TT_RELEASE_VERSION
    command: tt_regenerate_protocol

  utils-site-migrations:
    profiles:
      - workers
      - site

    command: tt_django migrate

  utils-site: {}

  utils-site-generate-static:
    command: tt_generate_static

  tt-diary:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-diary:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_diary/config.json:/home/tt_service/config.json

  tt-personal-messages: {}

  tt-storage:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-storage:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_storage/config.json:/home/tt_service/config.json

  tt-market:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-market:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_market/config.json:/home/tt_service/config.json

  tt-players-timers:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-timers:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_players_timers/config.json:/home/tt_service/config.json

  tt-personal-impacts:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_personal_impacts/config.json:/home/tt_service/config.json

  tt-crowd-impacts:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_crowd_impacts/config.json:/home/tt_service/config.json

  tt-job-impacts:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_job_impacts/config.json:/home/tt_service/config.json

  tt-fame-impacts:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_fame_impacts/config.json:/home/tt_service/config.json

  tt-game-chronicle:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-events-log:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_game_chronicle/config.json:/home/tt_service/config.json

  tt-clans-chronicle:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-events-log:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_clans_chronicle/config.json:/home/tt_service/config.json

  tt-money-spendings:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_money_spendings/config.json:/home/tt_service/config.json

  tt-emissaries-impacts:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_emissaries_impacts/config.json:/home/tt_service/config.json

  tt-players-properties:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-properties:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_players_properties/config.json:/home/tt_service/config.json

  tt-clans-properties:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-properties:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_clans_properties/config.json:/home/tt_service/config.json

  tt-matchmaker:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-matchmaker:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_matchmaker/config.json:/home/tt_service/config.json

  tt-places-effects:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-effects:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_places_effects/config.json:/home/tt_service/config.json

  tt-clans-currencies: {}

  tt-emissaries-events-currencies:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-bank:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_emissaries_events_currencies/config.json:/home/tt_service/config.json

  tt-emissaries-events-uniquer:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-uniquer:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_emissaries_events_uniquer/config.json:/home/tt_service/config.json

  tt-data-protector: {}

  site:
    command: tt_site -b 0.0.0.0:80 -w 4

    profiles:
      - site

    labels:
      org.the-tale.group: site
