networks:
  tt_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16


volumes:
  tt_site_static: {}
  tt_certbot_well_known: {}
  tt_certbot_storage: {}


services:

  core-postgresql:
    image: $TT_CONTAINERS_REGISTRY/the-tale/core-postgresql:$TT_RELEASE_VERSION

    volumes:
       - $TT_CONFIGS_ROOT/postgresql/postgresql.$TT_ENV.conf:/etc/postgresql/postgresql.conf:ro

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $TT_DB_ROOT_PASSWORD

    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  core-nginx:

    image: $TT_CONTAINERS_REGISTRY/the-tale/core-nginx:$TT_RELEASE_VERSION

    stop_grace_period: 1s

    volumes:
      - $TT_CONFIGS_ROOT/nginx/config.$TT_ENV.json:/root/nginx_config.json:ro
      - tt_certbot_well_known:/var/www/certbot/:ro
      - tt_certbot_storage:/etc/letsencrypt/:ro
      - tt_site_static:/var/www/site/:ro

    ports:
      - "80:80"
      - "443:443"

  utils-postgresql: {}

  utils-site-migrations:
    profiles:
      - workers
      - site

    command: tt_django migrate

  utils-site: {}

  utils-site-generate-static:
    command: tt_generate_static

  tt-personal-messages: {}

  tt-personal-impacts:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_personal_impacts/config.json:/home/tt_service/config.json

  tt-crowd-impacts:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_crowd_impacts/config.json:/home/tt_service/config.json

  tt-job-impacts:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_job_impacts/config.json:/home/tt_service/config.json

  tt-fame-impacts:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_fame_impacts/config.json:/home/tt_service/config.json

  tt-game-chronicle:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-events-log:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_game_chronicle/config.json:/home/tt_service/config.json

  tt-emissaries-impacts:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_emissaries_impacts/config.json:/home/tt_service/config.json

  tt-data-protector: {}

  site:
    command: tt_site -b 0.0.0.0:80 -w 4

    profiles:
      - site

    labels:
      org.the-tale.group: site
