volumes:
  postgresql-storage: {}
  postgresql-backups: {}


services:

  core-postgresql:
    volumes:
       - postgresql-storage:/var/lib/postgresql/data

  utils-postgresql:
    volumes:
       - postgresql-backups:/backups/

  core-postfix:

    volumes:
      - $TT_CONFIGS_ROOT/postfix/config.$TT_ENV.json:/root/postfix_config.json:ro

    ports:
      - "25:25"

  site:

    depends_on:
      - utils-site-generate-static
