# define services sceletons with help of yaml templating

x-site-image: &default-site-image
  image: $TT_CONTAINERS_REGISTRY/the-tale/site:$TT_RELEASE_VERSION


x-common: &default-common

  environment: &default-common-environment
    TT_WAIT_TIMEOUT: $TT_WAIT_TIMEOUT
    TT_SITE_STATIC_DIR: $TT_SITE_STATIC_DIR
    TT_SERVERS: $TT_SERVERS
    TT_DOMAINS: $TT_DOMAINS

  networks:
    tt_network: {}

x-core: &default-core
  << : *default-common

  labels:
    org.the-tale.group: core

  stop_grace_period: 1m

  profiles:
    - core

x-utils: &default-utils
  << : *default-common

  stop_grace_period: 1m

  labels:
    org.the-tale.group: utils

  volumes:
    # all utils containers must has access to static files foulder
    # they determine maintenance mode with its help
    - tt_site_static:/var/www/site/
    - $TT_CONFIGS_ROOT/the_tale/settings_local.py:/home/tt_service/repository/src/the_tale/the_tale/settings_local.py

  profiles:
    - utils

x-tt-service: &default-tt-service
  << : *default-common

  labels:
    org.the-tale.group: services

  command: tt_run_service

  stop_grace_period: 1s

  profiles:
    - services

x-the-tale: &default-the-tale
  << : [*default-site-image, *default-common]

  stop_grace_period: 1s

  volumes:
    # all site containers must has access to static files foulder
    # they determine maintenance mode with its help
    - tt_site_static:/var/www/site/
    - $TT_CONFIGS_ROOT/the_tale/settings_local.py:/home/tt_service/repository/src/the_tale/the_tale/settings_local.py

x-tt-personal-messages: &default-tt-personal-messages
  image: $TT_CONTAINERS_REGISTRY/the-tale/tt-personal-messages:$TT_RELEASE_VERSION

  volumes:
    - $TT_CONFIGS_ROOT/tt_personal_messages/config.json:/home/tt_service/config.json


x-tt-data-protector: &default-tt-data-protector
  image: $TT_CONTAINERS_REGISTRY/the-tale/tt-data-protector:$TT_RELEASE_VERSION

  volumes:
    - $TT_CONFIGS_ROOT/tt_data_protector/config.json:/home/tt_service/config.json


x-utils-postgresql: &default-utils-postgresql
    << : *default-utils

    image: $TT_CONTAINERS_REGISTRY/the-tale/utils-postgresql:$TT_RELEASE_VERSION

    volumes:
       - $TT_CONFIGS_ROOT/utils_postgresql/aws.config:/root/aws.config:ro

    environment:
      << : *default-common-environment

      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $TT_DB_ROOT_PASSWORD
      TT_DATABASES: $TT_DATABASES
      TT_S3_BACKET: $TT_BACKUP_S3_BACKET


# https://mindsers.blog/post/https-using-nginx-certbot-docker/
x-utils-certbot: &default-utils-certbot
    << : *default-utils

    image: $TT_CONTAINERS_REGISTRY/the-tale/utils-certbot:$TT_RELEASE_VERSION

    volumes:
      - tt_certbot_well_known:/var/www/certbot/
      - tt_certbot_storage:/etc/letsencrypt/
      - $TT_CONFIGS_ROOT/utils_certbot/cli.ini:/etc/letsencrypt/cli.ini:ro


services:

  core-postgresql:
    << : *default-core

  core-redis:
    << : *default-core

  core-nginx:
    << : *default-core

  core-postfix:
    << : *default-core

  utils-postgresql:
    << : *default-utils-postgresql

  utils-site:
    << : [*default-site-image, *default-utils]

  utils-site-migrations:
    << : [*default-site-image, *default-utils]

  utils-site-generate-static:
    << : [*default-site-image, *default-utils]

  tt-diary:
    << : *default-tt-service

  tt-personal-messages:
    << : [*default-tt-personal-messages, *default-tt-service]

  tt-personal-impacts:
    << : *default-tt-service

  tt-crowd-impacts:
    << : *default-tt-service

  tt-job-impacts:
    << : *default-tt-service

  tt-fame-impacts:
    << : *default-tt-service

  tt-game-chronicle:
    << : *default-tt-service

  tt-money-spendings:
    << : *default-tt-service

  tt-emissaries-impacts:
    << : *default-tt-service

  tt-players-properties:
    << : *default-tt-service

  tt-clans-properties:
    << : *default-tt-service

  tt-places-effects:
    << : *default-tt-service

  tt-data-protector:
    << : [*default-tt-data-protector, *default-tt-service]

  site:
    << : *default-the-tale
