services:

  core-postgresql:

    image: $TT_CONTAINERS_REGISTRY/the-tale/core-postgresql:$TT_RELEASE_VERSION

    build:
      context: ./postgresql
      labels:
        org.opencontainers.image.source: $TT_REPO

  utils-postgresql:

    image: $TT_CONTAINERS_REGISTRY/the-tale/utils-postgresql:$TT_RELEASE_VERSION

    build:
      context: ./utils_postgresql
      labels:
        org.opencontainers.image.source: $TT_REPO

      args:
        TT_BASE_IMAGE_VERSION: $TT_RELEASE_VERSION
        TT_CONTAINERS_REGISTRY: $TT_CONTAINERS_REGISTRY

  core-redis:

    image: $TT_CONTAINERS_REGISTRY/the-tale/core-redis:$TT_RELEASE_VERSION

    build:
      context: ./redis
      labels:
        org.opencontainers.image.source: $TT_REPO

  core-rabbitmq:

    image: $TT_CONTAINERS_REGISTRY/the-tale/core-rabbitmq:$TT_RELEASE_VERSION

    build:
      context: ./rabbitmq
      labels:
        org.opencontainers.image.source: $TT_REPO

  core-postfix:

    image: $TT_CONTAINERS_REGISTRY/the-tale/core-postfix:$TT_RELEASE_VERSION

    build:
      context: ./postfix
      labels:
        org.opencontainers.image.source: $TT_REPO

  core-nginx:

    image: $TT_CONTAINERS_REGISTRY/the-tale/core-nginx:$TT_RELEASE_VERSION

    build:
      context: ./nginx
      args:
        TT_SITE_STATIC_DIR: $TT_SITE_STATIC_DIR
        TT_CONTAINERS_REGISTRY: $TT_CONTAINERS_REGISTRY
      labels:
        org.opencontainers.image.source: $TT_REPO

  utils-certbot:

    image: $TT_CONTAINERS_REGISTRY/the-tale/utils-certbot:$TT_RELEASE_VERSION

    build:
      context: ./utils_certbot
      labels:
        org.opencontainers.image.source: $TT_REPO

  tt-base:

    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-base:$TT_RELEASE_VERSION

    build:
      context: ../
      dockerfile: ./docker/common/Dockerfile
      labels:
        org.opencontainers.image.source: $TT_REPO

  tt-diary:

    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-diary:$TT_RELEASE_VERSION

    build:
      context: ../
      dockerfile: ./docker/tt_service/Dockerfile
      args:
        TT_PACKAGE: tt_diary
        TT_BASE_IMAGE_VERSION: $TT_RELEASE_VERSION
        TT_CONTAINERS_REGISTRY: $TT_CONTAINERS_REGISTRY
      labels:
        org.opencontainers.image.source: $TT_REPO

  tt-personal-messages:

    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-personal-messages:$TT_RELEASE_VERSION

    build:
      context: ../
      dockerfile: ./docker/tt_service/Dockerfile
      args:
        TT_PACKAGE: tt_personal_messages
        TT_BASE_IMAGE_VERSION: $TT_RELEASE_VERSION
        TT_CONTAINERS_REGISTRY: $TT_CONTAINERS_REGISTRY
      labels:
        org.opencontainers.image.source: $TT_REPO

  tt-impacts:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    build:
      context: ../
      dockerfile: ./docker/tt_service/Dockerfile
      args:
        TT_PACKAGE: tt_impacts
        TT_BASE_IMAGE_VERSION: $TT_RELEASE_VERSION
        TT_CONTAINERS_REGISTRY: $TT_CONTAINERS_REGISTRY
      labels:
        org.opencontainers.image.source: $TT_REPO

  tt-events-log:

    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-events-log:$TT_RELEASE_VERSION

    build:
      context: ../
      dockerfile: ./docker/tt_service/Dockerfile
      args:
        TT_PACKAGE: tt_events_log
        TT_BASE_IMAGE_VERSION: $TT_RELEASE_VERSION
        TT_CONTAINERS_REGISTRY: $TT_CONTAINERS_REGISTRY
      labels:
        org.opencontainers.image.source: $TT_REPO

  tt-properties:

    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-properties:$TT_RELEASE_VERSION

    build:
      context: ../
      dockerfile: ./docker/tt_service/Dockerfile
      args:
        TT_PACKAGE: tt_properties
        TT_BASE_IMAGE_VERSION: $TT_RELEASE_VERSION
        TT_CONTAINERS_REGISTRY: $TT_CONTAINERS_REGISTRY
      labels:
        org.opencontainers.image.source: $TT_REPO

  tt-effects:

    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-effects:$TT_RELEASE_VERSION

    build:
      context: ../
      dockerfile: ./docker/tt_service/Dockerfile
      args:
        TT_PACKAGE: tt_effects
        TT_BASE_IMAGE_VERSION: $TT_RELEASE_VERSION
        TT_CONTAINERS_REGISTRY: $TT_CONTAINERS_REGISTRY
      labels:
        org.opencontainers.image.source: $TT_REPO

  tt-bank:

    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-bank:$TT_RELEASE_VERSION

    build:
      context: ../
      dockerfile: ./docker/tt_service/Dockerfile
      args:
        TT_PACKAGE: tt_bank
        TT_BASE_IMAGE_VERSION: $TT_RELEASE_VERSION
        TT_CONTAINERS_REGISTRY: $TT_CONTAINERS_REGISTRY
      labels:
        org.opencontainers.image.source: $TT_REPO

  tt-uniquer:

    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-uniquer:$TT_RELEASE_VERSION

    build:
      context: ../
      dockerfile: ./docker/tt_service/Dockerfile
      args:
        TT_PACKAGE: tt_uniquer
        TT_BASE_IMAGE_VERSION: $TT_RELEASE_VERSION
        TT_CONTAINERS_REGISTRY: $TT_CONTAINERS_REGISTRY
      labels:
        org.opencontainers.image.source: $TT_REPO

  tt-data-protector:

    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-data-protector:$TT_RELEASE_VERSION

    build:
      context: ../
      dockerfile: ./docker/tt_service/Dockerfile
      args:
        TT_PACKAGE: tt_data_protector
        TT_BASE_IMAGE_VERSION: $TT_RELEASE_VERSION
        TT_CONTAINERS_REGISTRY: $TT_CONTAINERS_REGISTRY
      labels:
        org.opencontainers.image.source: $TT_REPO

  site:

    image: $TT_CONTAINERS_REGISTRY/the-tale/site:$TT_RELEASE_VERSION

    build:
      context: ../
      dockerfile: ./docker/the_tale/Dockerfile
      args:
        TT_BASE_IMAGE_VERSION: $TT_RELEASE_VERSION
        TT_SITE_STATIC_DIR: $TT_SITE_STATIC_DIR
        TT_CONTAINERS_REGISTRY: $TT_CONTAINERS_REGISTRY
      labels:
        org.opencontainers.image.source: $TT_REPO
