# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0009_auto_20160319_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='places_history',
        ),
    ]
