# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 17:12
from __future__ import unicode_literals

import json

from django.db import migrations


def reset_preferences_couldowns(apps, schema_editor):
    for hero in apps.get_model("heroes", "Hero").objects.all():
        preferences = json.loads(hero.preferences)

        for data in preferences.itervalues():
            data['changed_at'] = 0

        hero.preferences = json.dumps(preferences, ensure_ascii=False)

        hero.save()


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0012_reset_quests_and_actions'),
    ]

    operations = [
        migrations.RunPython(reset_preferences_couldowns)
    ]
