# Generated by Django 2.2.10 on 2020-06-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20150520_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingplaces',
            name='gifts_returned_place',
        ),
        migrations.RemoveField(
            model_name='ratingvalues',
            name='gifts_returned',
        ),
    ]
