
import smart_imports

smart_imports.all()


class HTTP_METHOD(rels_django.DjangoEnum):
    records = (('CONNECT', 0, 'CONNECT'),
               ('DELETE', 1, 'DELETE'),
               ('GET', 2, 'GET'),
               ('HEAD', 3, 'HEAD'),
               ('OPTIONS', 4, 'OPTIONS'),
               ('POST', 5, 'POST'),
               ('PUT', 6, 'PUT'),
               ('PATCH', 7, 'PATCH'),
               ('TRACE', 8, 'TRACE') )


class HTTP_STATUS(rels_django.DjangoEnum):
    records = (
        ('CONTINUE', 100, 'CONTINUE'),
        ('SWITCHING_PROTOCOLS', 101, 'SWITCHING PROTOCOLS'),
        ('PROCESSING', 102, 'PROCESSING (WEBDAV; RFC 2518)'),

        ('OK', 200, 'OK'),
        ('CREATED', 201, 'CREATED'),
        ('ACCEPTED', 202, 'ACCEPTED'),
        ('NON_AUTHORITATIVE_INFORMATION', 203, 'NON-AUTHORITATIVE INFORMATION (SINCE HTTP/1.1)'),
        ('NO_CONTENT', 204, 'NO CONTENT'),
        ('RESET_CONTENT', 205, 'RESET CONTENT'),
        ('PARTIAL_CONTENT', 206, 'PARTIAL CONTENT'),
        ('MULTI_STATUS', 207, 'MULTI-STATUS (WEBDAV; RFC 4918)'),
        ('ALREADY_REPORTED', 208, 'ALREADY REPORTED (WEBDAV; RFC 5842)'),
        ('IM_USED', 226, 'IM USED (RFC 3229)'),

        ('MULTIPLE_CHOICES', 300, 'MULTIPLE CHOICES'),
        ('MOVED_PERMANENTLY', 301, 'MOVED PERMANENTLY'),
        ('FOUND', 302, 'FOUND'),
        ('SEE_OTHER', 303, 'SEE OTHER (SINCE HTTP/1.1)'),
        ('NOT_MODIFIED', 304, 'NOT MODIFIED'),
        ('USE_PROXY', 305, 'USE PROXY (SINCE HTTP/1.1)'),
        ('SWITCH_PROXY', 306, 'SWITCH PROXY'),
        ('TEMPORARY_REDIRECT', 307, 'TEMPORARY REDIRECT (SINCE HTTP/1.1)'),
        ('PERMANENT_REDIRECT', 308, 'PERMANENT REDIRECT (EXPERIMENTAL RFC; RFC 7238)'),
        ('BAD_REQUEST', 400, 'BAD REQUEST'),
        ('UNAUTHORIZED', 401, 'UNAUTHORIZED'),
        ('PAYMENT_REQUIRED', 402, 'PAYMENT REQUIRED'),
        ('FORBIDDEN', 403, 'FORBIDDEN'),
        ('NOT_FOUND', 404, 'NOT FOUND'),
        ('METHOD_NOT_ALLOWED', 405, 'METHOD NOT ALLOWED'),
        ('NOT_ACCEPTABLE', 406, 'NOT ACCEPTABLE'),
        ('PROXY_AUTHENTICATION_REQUIRED', 407, 'PROXY AUTHENTICATION REQUIRED'),
        ('REQUEST_TIMEOUT', 408, 'REQUEST TIMEOUT'),
        ('CONFLICT', 409, 'CONFLICT'),
        ('GONE', 410, 'GONE'),
        ('LENGTH_REQUIRED', 411, 'LENGTH REQUIRED'),
        ('PRECONDITION_FAILED', 412, 'PRECONDITION FAILED'),
        ('REQUEST_ENTITY_TOO_LARGE', 413, 'REQUEST ENTITY TOO LARGE'),
        ('REQUEST_URI_TOO_LONG', 414, 'REQUEST-URI TOO LONG'),
        ('UNSUPPORTED_MEDIA_TYPE', 415, 'UNSUPPORTED MEDIA TYPE'),
        ('REQUESTED_RANGE_NOT_SATISFIABLE', 416, 'REQUESTED RANGE NOT SATISFIABLE'),
        ('EXPECTATION_FAILED', 417, 'EXPECTATION FAILED'),
        ('IM_A_TEAPOT', 418, 'I\'M A TEAPOT (RFC 2324)'),
        ('AUTHENTICATION_TIMEOUT', 419, 'AUTHENTICATION TIMEOUT (NOT IN RFC 2616)'),
        ('UNPROCESSABLE_ENTITY', 422, 'UNPROCESSABLE ENTITY (WEBDAV; RFC 4918)'),
        ('LOCKED', 423, 'LOCKED (WEBDAV; RFC 4918)'),
        ('FAILED_DEPENDENCY', 424, 'FAILED DEPENDENCY (WEBDAV; RFC 4918)'),
        ('UPGRADE_REQUIRED', 426, 'UPGRADE REQUIRED'),
        ('PRECONDITION_REQUIRED', 428, 'PRECONDITION REQUIRED (RFC 6585)'),
        ('TOO_MANY_REQUESTS', 429, 'TOO MANY REQUESTS (RFC 6585)'),
        ('REQUEST_HEADER_FIELDS_TOO_LARGE', 431, 'REQUEST HEADER FIELDS TOO LARGE (RFC 6585)'),

        ('INTERNAL_SERVER_ERROR', 500, 'INTERNAL SERVER ERROR'),
        ('NOT_IMPLEMENTED', 501, 'NOT IMPLEMENTED'),
        ('BAD_GATEWAY', 502, 'BAD GATEWAY'),
        ('SERVICE_UNAVAILABLE', 503, 'SERVICE UNAVAILABLE'),
        ('GATEWAY_TIMEOUT', 504, 'GATEWAY TIMEOUT'),
        ('HTTP_VERSION_NOT_SUPPORTED', 505, 'HTTP VERSION NOT SUPPORTED'),
        ('VARIANT_ALSO_NEGOTIATES', 506, 'VARIANT ALSO NEGOTIATES (RFC 2295)'),
        ('INSUFFICIENT_STORAGE', 507, 'INSUFFICIENT STORAGE (WEBDAV; RFC 4918)'),
        ('LOOP_DETECTED', 508, 'LOOP DETECTED (WEBDAV; RFC 5842)'),
        ('NOT_EXTENDED', 510, 'NOT EXTENDED (RFC 2774)'),
        ('NETWORK_AUTHENTICATION_REQUIRED', 511, 'NETWORK AUTHENTICATION REQUIRED (RFC 6585)'),
    )
