# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-09 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0004_auto_20180609_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clan',
            options={'permissions': (('moderate_clan', 'Может редактировать кланы и т.п.'),)},
        ),
    ]
