# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-27 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0005_auto_20180609_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='active_members_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clan',
            name='might',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clan',
            name='premium_members_number',
            field=models.IntegerField(default=0),
        ),
    ]
