# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-27 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0006_auto_20181027_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='statistics_refreshed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
