# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-11-06 11:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0008_clan_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
    ]
