# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-11-06 12:10
from __future__ import unicode_literals

from django.db import migrations


def get_name(name):
    return {'forms': [name] * 18, 'type': 0, 'properties': {'3': 0, '2': 0, '1': 0}}


def fill_linguistics_name(apps, schema_editor):
    for clan in apps.get_model('clans', 'Clan').objects.all():

        clan.data = {'linguistics_name': get_name(clan.name)}

        clan.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0009_clan_data'),
    ]

    operations = [
        migrations.RunPython(
            fill_linguistics_name
        )
    ]
