# Generated by Django 2.1.15 on 2019-12-04 19:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0010_fill_linguistics_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
