# Generated by Django 2.2.10 on 2020-02-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0011_auto_20191204_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
