# Generated by Django 3.1.13 on 2021-11-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0012_auto_20200212_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='data',
            field=models.JSONField(),
        ),
    ]
