# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_add_political_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='out_game_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='state',
        ),
    ]
