# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_auto_20160412_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='enemies_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='friends_number',
        ),
    ]
