# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 10:41


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0013_fix_ruittar_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialconnection',
            name='out_game_at',
        ),
        migrations.RemoveField(
            model_name='socialconnection',
            name='out_game_at_turn',
        ),
        migrations.RemoveField(
            model_name='socialconnection',
            name='state',
        ),
    ]
