# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 12:29
from __future__ import unicode_literals

from django.db import migrations


def remove_social_connections(apps, schema_editor):
    apps.get_model("persons", "SocialConnection").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0014_auto_20160717_1041'),
    ]

    operations = [
        migrations.RunPython(remove_social_connections)
    ]
