# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobs', '0005_set_new_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobrecord',
            name='data',
            field=models.TextField(default='{}'),
        ),
    ]
