# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-24 17:43
from __future__ import unicode_literals

import json

from django.db import migrations


NEW_SIZES = {0: 3,
             1: 3,
             2: 4,
             3: 0,
             4: 3,
             5: 3,
             6: 1,
             7: 1,
             8: 3,
             9: 3,
             10: 3,
             11: 2,
             12: 2,
             13: 2,
             14: 2}


def fill_properties(apps, schema_editor):
    Mob = apps.get_model("mobs", "MobRecord")

    for mob in Mob.objects.all().iterator():
        data = json.loads(mob.data)

        data['features'] = [feature for feature in data.get('features', ()) if feature != 0]
        data['size'] = NEW_SIZES[data.get('size', 0)]
        data['orientation'] = 0 if data.get('body') in (1, 4) else 1

        mob.data = json.dumps(data)

        mob.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mobs', '0006_auto_20161019_1613'),
    ]

    operations = [
        migrations.RunPython(
            fill_properties,
        ),
    ]
