# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-09 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20161019_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='last_thread_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
