# Generated by Django 2.2.10 on 2020-05-28 15:27

from django.db import migrations


def remove(apps, schema_editor):
    apps.get_model("forum", "Post").objects.filter(state=1).update(text='')


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20180609_1713'),
    ]

    operations = [
        migrations.RunPython(remove)
    ]
