# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
import rels.django


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_at_turn', models.IntegerField(default=0)),
                ('saved_at_turn', models.IntegerField(default=0)),
                ('last_rare_operation_at_turn', models.IntegerField(default=0)),
                ('saved_at', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), auto_now=True)),
                ('is_fast', models.BooleanField(default=True, db_index=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_alive', models.BooleanField(default=True)),
                ('active_state_end_at', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), db_index=True)),
                ('premium_state_end_at', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), db_index=True)),
                ('ban_state_end_at', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), db_index=True)),
                ('ui_caching_started_at', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0), auto_now_add=True)),
                ('gender', rels.django.RelationIntegerField()),
                ('race', rels.django.RelationIntegerField()),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0.0)),
                ('raw_power_magic', models.BigIntegerField(default=0)),
                ('raw_power_physic', models.BigIntegerField(default=0)),
                ('money', models.BigIntegerField(default=0)),
                ('data', models.TextField(default=b'{}')),
                ('equipment', models.TextField(default=b'{}')),
                ('bag', models.TextField(default=b'{}')),
                ('abilities', models.TextField(default=b'', blank=True)),
                ('places_history', models.TextField(default=b'{}')),
                ('cards', models.TextField(default=b'{}')),
                ('messages', models.TextField(default=b'[]')),
                ('diary', models.TextField(default=b'[]')),
                ('actions', models.TextField(default=b'{}')),
                ('quests', models.TextField(default=b'{}')),
                ('quest_created_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), db_index=True)),
                ('settings_approved', models.BooleanField(default=True)),
                ('pvp', models.TextField(default=b'{}')),
                ('next_spending', rels.django.RelationIntegerField()),
                ('energy', models.IntegerField(default=0)),
                ('last_energy_regeneration_at_turn', models.IntegerField(default=0)),
                ('energy_bonus', models.BigIntegerField(default=0)),
                ('might', models.FloatField(default=0.0)),
                ('pos_percents', models.FloatField(default=None, null=True, blank=True)),
                ('pos_invert_direction', models.NullBooleanField(default=False)),
                ('pos_from_x', models.IntegerField(default=None, null=True, blank=True)),
                ('pos_from_y', models.IntegerField(default=None, null=True, blank=True)),
                ('pos_to_x', models.IntegerField(default=None, null=True, blank=True)),
                ('pos_to_y', models.IntegerField(default=None, null=True, blank=True)),
                ('preferences', models.TextField(default=b'{}')),
                ('habit_honor', models.FloatField(default=0)),
                ('habit_peacefulness', models.FloatField(default=0)),
                ('stat_pve_deaths', models.BigIntegerField(default=0)),
                ('stat_pve_kills', models.BigIntegerField(default=0)),
                ('stat_money_earned_from_loot', models.BigIntegerField(default=0)),
                ('stat_money_earned_from_artifacts', models.BigIntegerField(default=0)),
                ('stat_money_earned_from_quests', models.BigIntegerField(default=0)),
                ('stat_money_earned_from_help', models.BigIntegerField(default=0)),
                ('stat_money_earned_from_habits', models.BigIntegerField(default=0)),
                ('stat_money_earned_from_companions', models.BigIntegerField(default=0)),
                ('stat_money_spend_for_heal', models.BigIntegerField(default=0)),
                ('stat_money_spend_for_artifacts', models.BigIntegerField(default=0)),
                ('stat_money_spend_for_sharpening', models.BigIntegerField(default=0)),
                ('stat_money_spend_for_useless', models.BigIntegerField(default=0)),
                ('stat_money_spend_for_impact', models.BigIntegerField(default=0)),
                ('stat_money_spend_for_experience', models.BigIntegerField(default=0)),
                ('stat_money_spend_for_repairing', models.BigIntegerField(default=0)),
                ('stat_money_spend_for_tax', models.BigIntegerField(default=0)),
                ('stat_money_spend_for_companions', models.BigIntegerField(default=0)),
                ('stat_artifacts_had', models.BigIntegerField(default=0)),
                ('stat_loot_had', models.BigIntegerField(default=0)),
                ('stat_help_count', models.BigIntegerField(default=0)),
                ('stat_quests_done', models.BigIntegerField(default=0)),
                ('stat_companions_count', models.BigIntegerField(default=0)),
                ('stat_pvp_battles_1x1_number', models.BigIntegerField(default=0)),
                ('stat_pvp_battles_1x1_victories', models.BigIntegerField(default=0)),
                ('stat_pvp_battles_1x1_draws', models.BigIntegerField(default=0)),
                ('stat_cards_used', models.BigIntegerField(default=0)),
                ('stat_cards_combined', models.BigIntegerField(default=0)),
                ('stat_gifts_returned', models.BigIntegerField(default=0)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='HeroPreferences',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('energy_regeneration_type', models.IntegerField(default=0, blank=True, choices=[(0, '\u043c\u043e\u043b\u0438\u0442\u0432\u0430'), (1, '\u0436\u0435\u0440\u0442\u0432\u043e\u043f\u0440\u0438\u043d\u043e\u0448\u0435\u043d\u0438\u0435'), (2, '\u0431\u043b\u0430\u0433\u043e\u0432\u043e\u043d\u0438\u044f'), (3, '\u0441\u0438\u043c\u0432\u043e\u043b\u044b'), (4, '\u043c\u0435\u0434\u0438\u0442\u0430\u0446\u0438\u044f')])),
                ('equipment_slot', rels.django.RelationIntegerField(default=None, null=True, blank=True)),
                ('risk_level', rels.django.RelationIntegerField()),
                ('favorite_item', rels.django.RelationIntegerField(default=None, null=True, blank=True)),
                ('archetype', rels.django.RelationIntegerField(default=None, null=True, blank=True)),
                ('companion_dedication', rels.django.RelationIntegerField(default=None, null=True, blank=True)),
                ('companion_empathy', rels.django.RelationIntegerField(default=None, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
    ]
