# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 17:02
from __future__ import unicode_literals

import json

from django.db import migrations


def change_places_history_format(apps, schema_editor):
    for hero in apps.get_model("heroes", "Hero").objects.all().iterator():
        data = json.loads(hero.data)
        places_history = json.loads(hero.places_history)

        data['places_history'] = {'history': [(place_id, 1) for place_id in places_history['history']]}

        hero.data = json.dumps(data, ensure_ascii=True)
        hero.save()


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0007_extend_messages_arguments'),
    ]

    operations = [
        migrations.RunPython(change_places_history_format)
    ]
