# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0008_change_places_history_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='quests',
        ),
        migrations.AddField(
            model_name='hero',
            name='stat_money_earned_from_masters',
            field=models.BigIntegerField(default=0),
        ),
    ]
