# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 17:26
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


def make_id_equal_to_account_id(apps, schema_editor):
    Hero = apps.get_model("heroes", "Hero")
    HeroPreferences = apps.get_model("heroes", "HeroPreferences")

    for hero in Hero.objects.filter(id__lt=models.F('account_id')).order_by('-id').iterator():
        preferneces_id = HeroPreferences.objects.get(hero_id=hero.id).id

        HeroPreferences.objects.filter(id=preferneces_id).update(hero_id=1) # break dependency

        Hero.objects.filter(id=hero.id).update(id=hero.account_id)

        HeroPreferences.objects.filter(id=preferneces_id).update(hero_id=hero.account_id) # fix dependency


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0010_remove_hero_places_history'),
    ]

    operations = [
        migrations.RunPython(make_id_equal_to_account_id)
    ]
