# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0013_reset_preferences_couldown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='abilities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='hero',
            name='actions',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='actual_bills',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='bag',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='cards',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='data',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='diary',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='equipment',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='messages',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='preferences',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='pvp',
            field=models.TextField(default='{}'),
        ),
    ]
