# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0016_auto_20161030_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='pvp',
        ),
    ]
