# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0017_remove_hero_pvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='messages',
        ),
    ]
