# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 12:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0018_remove_hero_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='diary',
        ),
        migrations.AlterField(
            model_name='hero',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
    ]
