# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-20 18:03
from __future__ import unicode_literals

import json

from django.db import migrations


def load_data(apps, schema_editor):
    Hero = apps.get_model("heroes", "Hero")

    for hero in Hero.objects.iterator():
        hero.data = json.loads(hero.data)
        hero.save()


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0020_remove_hero_cards'),
    ]

    operations = [
        migrations.RunPython(
            load_data,
        ),
    ]
