# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-04 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0023_remove_middle_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='heroes.Hero')),
            ],
        ),
    ]
