# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-04 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0025_remove_hero_settings_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='pos_from_x',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='pos_from_y',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='pos_invert_direction',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='pos_percents',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='pos_place',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='pos_previous_place',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='pos_road',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='pos_to_x',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='pos_to_y',
        ),
    ]
