# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-11-06 12:06
from __future__ import unicode_literals

from django.db import migrations


def fill_clan_id(apps, schema_editor):
    for account_id, clan_id in apps.get_model("accounts", "Account").objects.values_list('id', 'clan_id'):
        if clan_id is None:
            continue

        apps.get_model("heroes", "Hero").objects.filter(id=account_id).update(clan_id=clan_id)


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0028_hero_clan_id'),
    ]

    operations = [
        migrations.RunPython(
            fill_clan_id
        )
    ]
