# Generated by Django 2.1.15 on 2019-12-04 19:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0029_fill_clan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='actions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='preferences',
            field=models.TextField(),
        ),
    ]
