# Generated by Django 2.2.10 on 2020-02-25 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_remove_building_integrity'),
        ('heroes', '0030_auto_20191204_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='heropreferences',
            name='quests_region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='places.Place'),
        ),
        migrations.AddField(
            model_name='heropreferences',
            name='quests_region_size',
            field=models.IntegerField(default=44),
        ),
    ]
