# Generated by Django 2.2.10 on 2020-03-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0031_auto_20200225_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heropreferences',
            name='quests_region_size',
            field=models.IntegerField(default=25),
        ),
    ]
