# Generated by Django 2.2.10 on 2020-03-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0032_auto_20200313_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='clan_id',
            new_name='clan',
        ),
    ]
