# Generated by Django 2.2.10 on 2020-06-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0033_auto_20200319_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='stat_gifts_returned',
        ),
    ]
