# Generated by Django 3.0.7 on 2020-06-16 14:38

from django.db import migrations


def remove(apps, schema_editor):
    apps.get_model("heroes", "Hero").objects.filter(next_spending=4).update(next_spending=1)


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0034_remove_hero_stat_gifts_returned'),
    ]

    operations = [
        migrations.RunPython(remove)
    ]
