# Generated by Django 3.0.7 on 2020-06-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0035_remove_spending_to_impacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='stat_help_count',
        ),
    ]
