# Generated by Django 3.0.7 on 2020-06-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0036_remove_hero_stat_help_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heropreferences',
            old_name='energy_regeneration_type',
            new_name='religion_type',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='last_energy_regeneration_at_turn',
        ),
    ]
