# Generated by Django 3.0.7 on 2020-06-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0037_auto_20200618_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='abilities',
        ),
    ]
