# Generated by Django 3.1.13 on 2021-11-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0038_remove_hero_abilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='data',
            field=models.JSONField(),
        ),
    ]
