# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-11 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0002_auto_20161019_1613'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waymark',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='waymark',
            name='point_from',
        ),
        migrations.RemoveField(
            model_name='waymark',
            name='point_to',
        ),
        migrations.RemoveField(
            model_name='waymark',
            name='road',
        ),
        migrations.RemoveField(
            model_name='road',
            name='exists',
        ),
        migrations.DeleteModel(
            name='Waymark',
        ),
    ]
