# Generated by Django 3.0.7 on 2020-06-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0003_auto_20181211_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='length',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
