# Generated by Django 3.0.7 on 2020-06-12 10:03

from django.db import migrations


def sync_length(apps, schema_editor):
    for road in apps.get_model("roads", "Road").objects.all():
        road.length = len(road.path)
        road.save()


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0004_auto_20200612_0957'),
    ]

    operations = [
        migrations.RunPython(sync_length)
    ]
