# Generated by Django 2.2.8 on 2020-05-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='property',
            index_together={('object_id', 'property_type')},
        ),
    ]
