# Generated by Django 2.2.8 on 2020-05-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_properties', '0002_auto_20200522_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='updated_at',
        ),
    ]
