# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 11:50
from __future__ import unicode_literals

from django.db import migrations


def remove_chronicle_templates(apps, schema_editor):
    Template = apps.get_model("linguistics", "Template")

    Template.objects.filter(key=260013).delete()
    Template.objects.filter(key=260030).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('linguistics', '0018_master_templates'),
    ]

    operations = [
        migrations.RunPython(
            remove_chronicle_templates,
        ),
    ]
