# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 18:21
from __future__ import unicode_literals

from django.db import migrations


def move_templates(apps, schema_editor):
    Template = apps.get_model("linguistics", "Template")

    for key_id in range(300000, 300005):
        Template.objects.filter(key=key_id).update(key=key_id+340000)


class Migration(migrations.Migration):

    dependencies = [
        ('linguistics', '0019_remove_chronicle_records'),
    ]

    operations = [
        migrations.RunPython(
            move_templates,
        ),
    ]
