# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 12:50
from __future__ import unicode_literals

from django.db import migrations
import rels.django


class Migration(migrations.Migration):

    dependencies = [
        ('linguistics', '0020_first_steps_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='used_in_status',
            field=rels.django.RelationIntegerField(db_index=True),
        ),
    ]
