# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-03 19:38
from __future__ import unicode_literals

from django.db import migrations


def remove_stock_up_energy(apps, schema_editor):
    Template = apps.get_model("linguistics", "Template")

    Template.objects.filter(key=240018).delete()
    Template.objects.filter(key=240019).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('linguistics', '0022_remove_building_repair_records'),
    ]

    operations = [
        migrations.RunPython(remove_stock_up_energy)
    ]
