# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-22 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguistics', '0023_remove_stock_up_energy_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='reward_given',
            field=models.BooleanField(default=False),
        ),
    ]
