# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-01 15:22
from __future__ import unicode_literals

from django.db import migrations


def remove_middle_gender(apps, schema_editor):
    apps.get_model("linguistics", "Restriction").objects.filter(group=0, external_id=2).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('linguistics', '0024_contribution_reward_given'),
        ('heroes', '0023_remove_middle_gender'),
    ]

    operations = [
        migrations.RunPython(
            remove_middle_gender,
        ),
    ]
