# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-17 10:35
from __future__ import unicode_literals

from django.db import migrations


def remove(apps, schema_editor):
    apps.get_model("linguistics", "Template").objects.filter(key=80034).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('linguistics', '0025_remove_middle_gender'),
    ]

    operations = [
        migrations.RunPython(remove)
    ]
