# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-05-03 13:47
from __future__ import unicode_literals

from django.db import migrations


def remove(apps, schema_editor):
    apps.get_model("linguistics", "Template").objects.filter(key__in=(240000, 240001)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('linguistics', '0026_remove_action_inplace_companion_leave_key'),
    ]

    operations = [
        migrations.RunPython(remove)
    ]
