# Generated by Django 2.2.10 on 2020-02-11 09:12

from django.db import migrations


def remove(apps, schema_editor):
    apps.get_model("linguistics", "Template").objects.filter(key__in=[620000,
                                                                      620001,
                                                                      620002,
                                                                      620003,
                                                                      620004,
                                                                      620005,
                                                                      620006,
                                                                      620007,
                                                                      620008,
                                                                      620018,
                                                                      620019,
                                                                      620020,
                                                                      620021,
                                                                      620022,
                                                                      620023,
                                                                      620024,
                                                                      620025,
                                                                      620026,
                                                                      620027,
                                                                      620028,
                                                                      620029,
                                                                      620030,
                                                                      620031,
                                                                      620032,
                                                                      620033,
                                                                      620034,
                                                                      620035,
                                                                      620036,
                                                                      620037,
                                                                      620038,
                                                                      620039,
                                                                      620040,
                                                                      620041,
                                                                      620042,
                                                                      620043,
                                                                      620044,
                                                                      620045,
                                                                      620046,
                                                                      620047,
                                                                      620048,
                                                                      620049,
                                                                      620050,
                                                                      620051,
                                                                      620052,
                                                                      620053,
                                                                      620090,
                                                                      620092,
                                                                      620093,
                                                                      620094,
                                                                      620095]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('linguistics', '0027_remove_deprecated_pvp_templates'),
    ]

    operations = [
        migrations.RunPython(remove)
    ]
