# Generated by Django 3.0.7 on 2020-06-18 13:56

from django.db import migrations


def move(apps, schema_editor):
    Template = apps.get_model("linguistics", "Template")

    Template.objects.filter(key=240009).update(key=240008)
    Template.objects.filter(key=240011).update(key=240010)
    Template.objects.filter(key=240013).update(key=240012)
    Template.objects.filter(key=240021).update(key=240020)


class Migration(migrations.Migration):

    dependencies = [
        ('linguistics', '0029_remove_deprecated_templates'),
    ]

    operations = [
        migrations.RunPython(move)
    ]
