# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-09 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0003_auto_20180609_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='forum_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.SubCategory'),
        ),
    ]
