# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-03 19:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.PositiveIntegerField(db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction', models.UUIDField(default=uuid.uuid4)),
                ('item', models.UUIDField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'log_records',
            },
        ),
    ]
