# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-09 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='base_type',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='full_type',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
