# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-09 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_storage', '0002_auto_20170509_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrecord',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
