# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-26 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_storage', '0003_logrecord_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='storage',
            field=models.IntegerField(default=0),
        ),
    ]
