# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-17 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_storage', '0004_item_storage'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='logrecord',
            index_together=set([('item', 'created_at')]),
        ),
    ]
