# Generated by Django 3.0.11 on 2021-10-18 08:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt_storage', '0005_auto_20190417_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
