# Generated by Django 3.1.13 on 2021-11-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_storage', '0006_auto_20211018_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
