# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-13 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_events_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtag',
            name='event',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
