# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-13 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_events_log', '0002_auto_20180913_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtag',
            name='created_at_turn',
            field=models.BigIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
