# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 15:02
from __future__ import unicode_literals

from django.db import migrations


def add_none_specialization(apps, schema_editor):
    apps.get_model("places", "Place").objects.filter(modifier=None).update(modifier=9)


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_scale_power'),
    ]

    operations = [
        migrations.RunPython(add_none_specialization)
    ]
