# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-07 12:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('owner', models.BigIntegerField()),
                ('entity', models.BigIntegerField()),
                ('type', models.IntegerField()),
                ('speed', models.FloatField()),
                ('resources', models.FloatField()),
                ('border', models.FloatField()),
                ('resources_at', models.DateTimeField(auto_now_add=True)),
                ('finish_at', models.DateTimeField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default='{}')),
                ('restarted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'timers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='timer',
            unique_together=set([('owner', 'entity', 'type')]),
        ),
    ]
