# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 14:52
from __future__ import unicode_literals

from django.db import migrations

def remove_bills_for_remove_person(apps, schema_editor):
    Bill = apps.get_model("bills", "Bill")
    Bill.objects.filter(state=1, type=1).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20150602_1019'),
    ]

    operations = [
        migrations.RunPython(
            remove_bills_for_remove_person
        ),
    ]
