# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_remove_bills_for_remove_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='applyed_at_turn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
