# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_auto_20160424_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'permissions': (('moderate_bill', 'Может администрировать записи в Книге Судеб'),)},
        ),
    ]
