# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-30 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_auto_20170130_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='rationale',
        ),
    ]
