# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-26 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_remove_bill_rationale'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='depends_on',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bills.Bill'),
        ),
    ]
