# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='section',
            field=models.CharField(choices=[('test', 'Тест'), ('world', 'Мифология'), ('development', 'Разработка')], db_index=True, default=None, max_length=16),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256),
        ),
    ]
