# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-10 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20161019_1613'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='page',
            name='author',
        ),
        migrations.RemoveField(
            model_name='page',
            name='editor',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
