# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 12:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_messages_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_1', models.PositiveIntegerField()),
                ('account_2', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True, default='')),
                ('sender', models.PositiveIntegerField()),
                ('recipients', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Visibility',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.PositiveIntegerField()),
                ('visible', models.BooleanField(default=True)),
                ('message', models.ForeignKey(db_column='message', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tt_personal_messages.Message')),
            ],
            options={
                'db_table': 'visibilities',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='message',
            field=models.ForeignKey(db_column='message', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tt_personal_messages.Message'),
        ),
        migrations.AlterUniqueTogether(
            name='visibility',
            unique_together=set([('account', 'message')]),
        ),
        migrations.AlterIndexTogether(
            name='visibility',
            index_together=set([('account', 'visible')]),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set([('account_1', 'account_2', 'message')]),
        ),
    ]
