# Generated by Django 2.2.8 on 2020-05-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_personal_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visibility',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
