
from rels.django import DjangoEnum

from dext.common.utils import s11n

from django.core.management.base import BaseCommand

from tt_logic.beings.relations import BODY, FEATURE, MOVEMENT, SIZE, STRUCTURE
from the_tale.game.artifacts.relations import STANDARD_WEAPON

from the_tale.game.mobs import models


MOBS = [
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_42, FEATURE.FEATURE_0],
  'id': 29,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_0,
  'weapon': STANDARD_WEAPON.WEAPON_13},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_15, FEATURE.FEATURE_45],
  'id': 155,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_7,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_13},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_42, FEATURE.FEATURE_0],
  'id': 45,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_3,
  'weapon': STANDARD_WEAPON.WEAPON_13},
 {'body': BODY.BODY_18,
  'features': [FEATURE.FEATURE_21, FEATURE.FEATURE_46],
  'id': 42,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_3,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_47],
  'id': 33,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_1,
  'weapon': STANDARD_WEAPON.WEAPON_16},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_15, FEATURE.FEATURE_45, FEATURE.FEATURE_47],
  'id': 22,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_9,
  'features': [FEATURE.FEATURE_23],
  'id': 53,
  'movement': MOVEMENT.MOVEMENT_5,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_7,
  'weapon': STANDARD_WEAPON.WEAPON_3},
 {'body': BODY.BODY_9,
  'features': [FEATURE.FEATURE_23],
  'id': 39,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_7,
  'weapon': STANDARD_WEAPON.WEAPON_26},
 {'body': BODY.BODY_10,
  'features': [FEATURE.FEATURE_23, FEATURE.FEATURE_2],
  'id': 96,
  'movement': MOVEMENT.MOVEMENT_6,
  'size': SIZE.SIZE_9,
  'structure': STRUCTURE.STRUCTURE_7,
  'weapon': STANDARD_WEAPON.WEAPON_3},
 {'body': BODY.BODY_10,
  'features': [FEATURE.FEATURE_23, FEATURE.FEATURE_2],
  'id': 128,
  'movement': MOVEMENT.MOVEMENT_6,
  'size': SIZE.SIZE_9,
  'structure': STRUCTURE.STRUCTURE_7,
  'weapon': STANDARD_WEAPON.WEAPON_3},
 {'body': BODY.BODY_13,
  'features': [FEATURE.FEATURE_23, FEATURE.FEATURE_0, FEATURE.FEATURE_47],
  'id': 172,
  'movement': MOVEMENT.MOVEMENT_7,
  'size': SIZE.SIZE_4,
  'structure': STRUCTURE.STRUCTURE_7,
  'weapon': STANDARD_WEAPON.WEAPON_3},
 {'body': BODY.BODY_9,
  'features': [FEATURE.FEATURE_23, FEATURE.FEATURE_47],
  'id': 36,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_7,
  'weapon': STANDARD_WEAPON.WEAPON_8},
 {'body': BODY.BODY_13,
  'features': [FEATURE.FEATURE_23, FEATURE.FEATURE_47],
  'id': 127,
  'movement': MOVEMENT.MOVEMENT_7,
  'size': SIZE.SIZE_4,
  'structure': STRUCTURE.STRUCTURE_7,
  'weapon': STANDARD_WEAPON.WEAPON_3},
 {'body': BODY.BODY_9,
  'features': [FEATURE.FEATURE_23, FEATURE.FEATURE_20],
  'id': 122,
  'movement': MOVEMENT.MOVEMENT_5,
  'size': SIZE.SIZE_9,
  'structure': STRUCTURE.STRUCTURE_7,
  'weapon': STANDARD_WEAPON.WEAPON_3},
 {'body': BODY.BODY_10,
  'features': [FEATURE.FEATURE_23, FEATURE.FEATURE_2],
  'id': 196,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_7,
  'weapon': STANDARD_WEAPON.WEAPON_8},
 {'body': BODY.BODY_9,
  'features': [FEATURE.FEATURE_23, FEATURE.FEATURE_2],
  'id': 143,
  'movement': MOVEMENT.MOVEMENT_5,
  'size': SIZE.SIZE_8,
  'structure': STRUCTURE.STRUCTURE_7,
  'weapon': STANDARD_WEAPON.WEAPON_3},
 {'body': BODY.BODY_9,
  'features': [FEATURE.FEATURE_23, FEATURE.FEATURE_47, FEATURE.FEATURE_46],
  'id': 49,
  'movement': MOVEMENT.MOVEMENT_6,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_7,
  'weapon': STANDARD_WEAPON.WEAPON_2},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_19,
               FEATURE.FEATURE_43,
               FEATURE.FEATURE_47,
               FEATURE.FEATURE_26,
               FEATURE.FEATURE_4],
  'id': 199,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_19},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_43,
               FEATURE.FEATURE_45,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_10,
               FEATURE.FEATURE_30,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_15],
  'id': 75,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_43,
               FEATURE.FEATURE_26,
               FEATURE.FEATURE_47,
               FEATURE.FEATURE_21],
  'id': 81,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_10,
               FEATURE.FEATURE_26,
               FEATURE.FEATURE_47,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_11],
  'id': 163,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_4,
               FEATURE.FEATURE_26,
               FEATURE.FEATURE_42,
               FEATURE.FEATURE_21],
  'id': 182,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_18},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_10,
               FEATURE.FEATURE_26,
               FEATURE.FEATURE_47,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_25,
               FEATURE.FEATURE_11],
  'id': 161,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_4,
               FEATURE.FEATURE_26,
               FEATURE.FEATURE_42,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_19,
               FEATURE.FEATURE_20],
  'id': 171,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_4,
               FEATURE.FEATURE_26,
               FEATURE.FEATURE_47,
               FEATURE.FEATURE_21],
  'id': 107,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_6, FEATURE.FEATURE_11],
  'id': 197,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_4,
  'weapon': STANDARD_WEAPON.WEAPON_4},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_29,
               FEATURE.FEATURE_17,
               FEATURE.FEATURE_4,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_15],
  'id': 103,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_10,
               FEATURE.FEATURE_20,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_11],
  'id': 106,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_23},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_29,
               FEATURE.FEATURE_20,
               FEATURE.FEATURE_19,
               FEATURE.FEATURE_4,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_15],
  'id': 191,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_19, FEATURE.FEATURE_4, FEATURE.FEATURE_26],
  'id': 65,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_13},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_7, FEATURE.FEATURE_11, FEATURE.FEATURE_40],
  'id': 64,
  'movement': MOVEMENT.MOVEMENT_8,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_4,
  'weapon': STANDARD_WEAPON.WEAPON_4},
 {'body': BODY.BODY_1,
  'features': [],
  'id': 2,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_4,
  'weapon': STANDARD_WEAPON.WEAPON_4},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_6,
               FEATURE.FEATURE_26,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_11],
  'id': 192,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_15,
               FEATURE.FEATURE_42,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_8,
               FEATURE.FEATURE_19],
  'id': 198,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_4,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_0},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_26, FEATURE.FEATURE_21, FEATURE.FEATURE_44],
  'id': 158,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_4},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_15,
               FEATURE.FEATURE_4,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_27,
               FEATURE.FEATURE_29],
  'id': 27,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_6,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_7, FEATURE.FEATURE_11, FEATURE.FEATURE_40],
  'id': 167,
  'movement': MOVEMENT.MOVEMENT_8,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_4,
  'weapon': STANDARD_WEAPON.WEAPON_4},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_50,
               FEATURE.FEATURE_47,
               FEATURE.FEATURE_36,
               FEATURE.FEATURE_46],
  'id': 84,
  'movement': MOVEMENT.MOVEMENT_0,
  'size': SIZE.SIZE_7,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_21,
               FEATURE.FEATURE_2,
               FEATURE.FEATURE_36,
               FEATURE.FEATURE_27,
               FEATURE.FEATURE_12],
  'id': 170,
  'movement': MOVEMENT.MOVEMENT_0,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_18},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_21, FEATURE.FEATURE_43],
  'id': 102,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_21, FEATURE.FEATURE_28, FEATURE.FEATURE_42],
  'id': 101,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_22},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_11,
               FEATURE.FEATURE_6,
               FEATURE.FEATURE_43,
               FEATURE.FEATURE_27,
               FEATURE.FEATURE_39,
               FEATURE.FEATURE_15],
  'id': 203,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_13},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_21, FEATURE.FEATURE_44, FEATURE.FEATURE_36],
  'id': 3,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_2},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_21, FEATURE.FEATURE_43, FEATURE.FEATURE_47],
  'id': 105,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_4},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_21, FEATURE.FEATURE_16],
  'id': 110,
  'movement': MOVEMENT.MOVEMENT_0,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_5,
  'features': [FEATURE.FEATURE_11,
               FEATURE.FEATURE_8,
               FEATURE.FEATURE_51,
               FEATURE.FEATURE_21],
  'id': 204,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_21,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_24,
               FEATURE.FEATURE_19],
  'id': 202,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_0},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_44, FEATURE.FEATURE_47],
  'id': 71,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_5},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_42, FEATURE.FEATURE_19, FEATURE.FEATURE_21],
  'id': 61,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_16,
  'features': [FEATURE.FEATURE_51,
               FEATURE.FEATURE_7,
               FEATURE.FEATURE_48,
               FEATURE.FEATURE_19,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_21],
  'id': 94,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_10,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_16,
  'features': [FEATURE.FEATURE_21, FEATURE.FEATURE_46, FEATURE.FEATURE_48],
  'id': 78,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_8,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_5,
  'features': [FEATURE.FEATURE_46, FEATURE.FEATURE_21, FEATURE.FEATURE_50],
  'id': 132,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_16,
  'features': [FEATURE.FEATURE_46, FEATURE.FEATURE_21, FEATURE.FEATURE_52],
  'id': 7,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_5,
  'features': [FEATURE.FEATURE_46, FEATURE.FEATURE_21, FEATURE.FEATURE_52],
  'id': 148,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_8,
  'features': [FEATURE.FEATURE_51,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_19],
  'id': 34,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_5,
  'features': [FEATURE.FEATURE_36,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_50],
  'id': 165,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_16,
  'features': [FEATURE.FEATURE_52,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_47,
               FEATURE.FEATURE_19,
               FEATURE.FEATURE_21],
  'id': 147,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_16,
  'features': [FEATURE.FEATURE_51,
               FEATURE.FEATURE_52,
               FEATURE.FEATURE_19,
               FEATURE.FEATURE_0,
               FEATURE.FEATURE_21],
  'id': 189,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_8,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_16,
  'features': [FEATURE.FEATURE_49,
               FEATURE.FEATURE_10,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_11],
  'id': 130,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_6,
  'features': [FEATURE.FEATURE_10,
               FEATURE.FEATURE_49,
               FEATURE.FEATURE_50,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_11],
  'id': 62,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_5,
  'features': [FEATURE.FEATURE_24,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_44,
               FEATURE.FEATURE_21],
  'id': 93,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_0,
  'features': [FEATURE.FEATURE_48, FEATURE.FEATURE_35, FEATURE.FEATURE_0],
  'id': 190,
  'movement': MOVEMENT.MOVEMENT_3,
  'size': SIZE.SIZE_5,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_21},
 {'body': BODY.BODY_8,
  'features': [FEATURE.FEATURE_49,
               FEATURE.FEATURE_0,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_52],
  'id': 11,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_9,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_0,
  'features': [FEATURE.FEATURE_48, FEATURE.FEATURE_35, FEATURE.FEATURE_0],
  'id': 125,
  'movement': MOVEMENT.MOVEMENT_3,
  'size': SIZE.SIZE_5,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_21},
 {'body': BODY.BODY_16,
  'features': [FEATURE.FEATURE_11,
               FEATURE.FEATURE_8,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_39],
  'id': 51,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_18,
  'features': [FEATURE.FEATURE_52, FEATURE.FEATURE_46, FEATURE.FEATURE_21],
  'id': 67,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_8,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_18,
  'features': [FEATURE.FEATURE_48, FEATURE.FEATURE_46, FEATURE.FEATURE_21],
  'id': 159,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_10,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_5,
  'features': [FEATURE.FEATURE_46,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_52,
               FEATURE.FEATURE_19],
  'id': 120,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_8,
  'features': [FEATURE.FEATURE_21, FEATURE.FEATURE_46, FEATURE.FEATURE_48],
  'id': 146,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_3,
  'features': [FEATURE.FEATURE_21,
               FEATURE.FEATURE_49,
               FEATURE.FEATURE_52,
               FEATURE.FEATURE_46],
  'id': 138,
  'movement': MOVEMENT.MOVEMENT_10,
  'size': SIZE.SIZE_4,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_5,
  'features': [FEATURE.FEATURE_46,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_16,
               FEATURE.FEATURE_50,
               FEATURE.FEATURE_52],
  'id': 115,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_10,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_5,
  'features': [FEATURE.FEATURE_46,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_52,
               FEATURE.FEATURE_50],
  'id': 133,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_10,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_5,
  'features': [FEATURE.FEATURE_46,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_52,
               FEATURE.FEATURE_50,
               FEATURE.FEATURE_44],
  'id': 169,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_10,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_16,
  'features': [FEATURE.FEATURE_52, FEATURE.FEATURE_46, FEATURE.FEATURE_21],
  'id': 48,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_33],
  'id': 142,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_17},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_33],
  'id': 92,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_14},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_34],
  'id': 12,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_14},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_33, FEATURE.FEATURE_1, FEATURE.FEATURE_18],
  'id': 63,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_15},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_32, FEATURE.FEATURE_5],
  'id': 58,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_23},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_34],
  'id': 40,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_6},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_33],
  'id': 10,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_12},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_33],
  'id': 88,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_14},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_0,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_17,
               FEATURE.FEATURE_42,
               FEATURE.FEATURE_45,
               FEATURE.FEATURE_8,
               FEATURE.FEATURE_27],
  'id': 162,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_4,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_33],
  'id': 35,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_14},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_15, FEATURE.FEATURE_32, FEATURE.FEATURE_18],
  'id': 129,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_0},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_33],
  'id': 113,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_23},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_32, FEATURE.FEATURE_1, FEATURE.FEATURE_18],
  'id': 117,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_12},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_47,
               FEATURE.FEATURE_43,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_16],
  'id': 72,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_7,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_15},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_11,
               FEATURE.FEATURE_15,
               FEATURE.FEATURE_49,
               FEATURE.FEATURE_52,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_21],
  'id': 90,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_47, FEATURE.FEATURE_32, FEATURE.FEATURE_18],
  'id': 80,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_4,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_7},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_42,
               FEATURE.FEATURE_15,
               FEATURE.FEATURE_51,
               FEATURE.FEATURE_52,
               FEATURE.FEATURE_45],
  'id': 77,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_42, FEATURE.FEATURE_1, FEATURE.FEATURE_34],
  'id': 153,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_23},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_15, FEATURE.FEATURE_32, FEATURE.FEATURE_29],
  'id': 66,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_7,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_1},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_15,
               FEATURE.FEATURE_32,
               FEATURE.FEATURE_17,
               FEATURE.FEATURE_45],
  'id': 99,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_7,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_24},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_42,
               FEATURE.FEATURE_1,
               FEATURE.FEATURE_18,
               FEATURE.FEATURE_33],
  'id': 43,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_23},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_33, FEATURE.FEATURE_18, FEATURE.FEATURE_47],
  'id': 60,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_19},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_42,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_41,
               FEATURE.FEATURE_0,
               FEATURE.FEATURE_12,
               FEATURE.FEATURE_15],
  'id': 131,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_13},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_42,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_2,
               FEATURE.FEATURE_45,
               FEATURE.FEATURE_0,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_28],
  'id': 108,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_0,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_13},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_33],
  'id': 109,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_14},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_34],
  'id': 141,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_14},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_43, FEATURE.FEATURE_47, FEATURE.FEATURE_34],
  'id': 38,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_15},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_17,
               FEATURE.FEATURE_47,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_9,
               FEATURE.FEATURE_46],
  'id': 28,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_8,
               FEATURE.FEATURE_15,
               FEATURE.FEATURE_18,
               FEATURE.FEATURE_47,
               FEATURE.FEATURE_28],
  'id': 151,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_7,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_15},
 {'body': BODY.BODY_10,
  'features': [FEATURE.FEATURE_23,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_10,
               FEATURE.FEATURE_45,
               FEATURE.FEATURE_33],
  'id': 194,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_47,
               FEATURE.FEATURE_9,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_32],
  'id': 111,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_0,
               FEATURE.FEATURE_50,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_18,
               FEATURE.FEATURE_42,
               FEATURE.FEATURE_45,
               FEATURE.FEATURE_9],
  'id': 160,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_0,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_15,
               FEATURE.FEATURE_42,
               FEATURE.FEATURE_4,
               FEATURE.FEATURE_18,
               FEATURE.FEATURE_26,
               FEATURE.FEATURE_32],
  'id': 201,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_7,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_22},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_5, FEATURE.FEATURE_33],
  'id': 37,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_15},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_33, FEATURE.FEATURE_18],
  'id': 114,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_23},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_34],
  'id': 150,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_19},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_34],
  'id': 149,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_12},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_32,
               FEATURE.FEATURE_50,
               FEATURE.FEATURE_51,
               FEATURE.FEATURE_18,
               FEATURE.FEATURE_15],
  'id': 145,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_0},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_11,
               FEATURE.FEATURE_15,
               FEATURE.FEATURE_49,
               FEATURE.FEATURE_52,
               FEATURE.FEATURE_42,
               FEATURE.FEATURE_21],
  'id': 91,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_4,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_21,
               FEATURE.FEATURE_17,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_26,
               FEATURE.FEATURE_33,
               FEATURE.FEATURE_45],
  'id': 31,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_7,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_18, FEATURE.FEATURE_33],
  'id': 50,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_22},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_4, FEATURE.FEATURE_33],
  'id': 112,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_15},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_15, FEATURE.FEATURE_47, FEATURE.FEATURE_50],
  'id': 166,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_33],
  'id': 44,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_12},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_34, FEATURE.FEATURE_26],
  'id': 156,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_19},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_33, FEATURE.FEATURE_5],
  'id': 41,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_19},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_33],
  'id': 52,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_14},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_34],
  'id': 70,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_18},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_33],
  'id': 30,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_7,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_6},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_33, FEATURE.FEATURE_5],
  'id': 152,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_23},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_34, FEATURE.FEATURE_5],
  'id': 47,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_19},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_33, FEATURE.FEATURE_1],
  'id': 140,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_23},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_34, FEATURE.FEATURE_5],
  'id': 89,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_14},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_34],
  'id': 68,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_14},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_34],
  'id': 46,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_22},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_34],
  'id': 154,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_6},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_9, FEATURE.FEATURE_11],
  'id': 9,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_6},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_32,
               FEATURE.FEATURE_15,
               FEATURE.FEATURE_42,
               FEATURE.FEATURE_13],
  'id': 200,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_4,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_23},
 {'body': BODY.BODY_2,
  'features': [FEATURE.FEATURE_0, FEATURE.FEATURE_22, FEATURE.FEATURE_12],
  'id': 6,
  'movement': MOVEMENT.MOVEMENT_9,
  'size': SIZE.SIZE_0,
  'structure': STRUCTURE.STRUCTURE_1,
  'weapon': STANDARD_WEAPON.WEAPON_13},
 {'body': BODY.BODY_2,
  'features': [FEATURE.FEATURE_22, FEATURE.FEATURE_47],
  'id': 21,
  'movement': MOVEMENT.MOVEMENT_9,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_1,
  'weapon': STANDARD_WEAPON.WEAPON_25},
 {'body': BODY.BODY_2,
  'features': [FEATURE.FEATURE_22, FEATURE.FEATURE_47],
  'id': 116,
  'movement': MOVEMENT.MOVEMENT_9,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_1,
  'weapon': STANDARD_WEAPON.WEAPON_25},
 {'body': BODY.BODY_2,
  'features': [FEATURE.FEATURE_22, FEATURE.FEATURE_47],
  'id': 4,
  'movement': MOVEMENT.MOVEMENT_9,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_1,
  'weapon': STANDARD_WEAPON.WEAPON_25},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_46,
               FEATURE.FEATURE_23,
               FEATURE.FEATURE_7,
               FEATURE.FEATURE_11],
  'id': 15,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_17,
  'features': [FEATURE.FEATURE_40],
  'id': 135,
  'movement': MOVEMENT.MOVEMENT_8,
  'size': SIZE.SIZE_3,
  'structure': STRUCTURE.STRUCTURE_4,
  'weapon': STANDARD_WEAPON.WEAPON_4},
 {'body': BODY.BODY_5,
  'features': [FEATURE.FEATURE_40, FEATURE.FEATURE_47],
  'id': 79,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_4,
  'weapon': STANDARD_WEAPON.WEAPON_4},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_11,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_36,
               FEATURE.FEATURE_42],
  'id': 57,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_4,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_47, FEATURE.FEATURE_40, FEATURE.FEATURE_12],
  'id': 8,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_4,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_12],
  'id': 82,
  'movement': MOVEMENT.MOVEMENT_8,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_4,
  'weapon': STANDARD_WEAPON.WEAPON_4},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_47,
               FEATURE.FEATURE_12,
               FEATURE.FEATURE_26,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_43],
  'id': 104,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_4},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_11],
  'id': 83,
  'movement': MOVEMENT.MOVEMENT_8,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_4,
  'weapon': STANDARD_WEAPON.WEAPON_4},
 {'body': BODY.BODY_16,
  'features': [FEATURE.FEATURE_7,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_52,
               FEATURE.FEATURE_46],
  'id': 14,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_18,
  'features': [FEATURE.FEATURE_10,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_24,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_39,
               FEATURE.FEATURE_44,
               FEATURE.FEATURE_47],
  'id': 55,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_4,
  'features': [],
  'id': 59,
  'movement': MOVEMENT.MOVEMENT_8,
  'size': SIZE.SIZE_0,
  'structure': STRUCTURE.STRUCTURE_4,
  'weapon': STANDARD_WEAPON.WEAPON_4},
 {'body': BODY.BODY_18,
  'features': [FEATURE.FEATURE_0,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_28,
               FEATURE.FEATURE_6,
               FEATURE.FEATURE_11],
  'id': 32,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_10,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_18,
  'features': [FEATURE.FEATURE_0,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_28,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_17],
  'id': 24,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_5,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_18,
  'features': [FEATURE.FEATURE_4,
               FEATURE.FEATURE_25,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_46],
  'id': 16,
  'movement': MOVEMENT.MOVEMENT_1,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_3,
  'features': [FEATURE.FEATURE_8,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_47,
               FEATURE.FEATURE_24,
               FEATURE.FEATURE_46],
  'id': 54,
  'movement': MOVEMENT.MOVEMENT_10,
  'size': SIZE.SIZE_1,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_3,
  'features': [FEATURE.FEATURE_8,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_47,
               FEATURE.FEATURE_24,
               FEATURE.FEATURE_46],
  'id': 144,
  'movement': MOVEMENT.MOVEMENT_10,
  'size': SIZE.SIZE_1,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_18,
  'features': [FEATURE.FEATURE_0,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_28,
               FEATURE.FEATURE_6,
               FEATURE.FEATURE_11],
  'id': 100,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_10,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_3,
  'features': [FEATURE.FEATURE_8,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_0,
               FEATURE.FEATURE_24,
               FEATURE.FEATURE_46],
  'id': 123,
  'movement': MOVEMENT.MOVEMENT_10,
  'size': SIZE.SIZE_2,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_3,
  'features': [FEATURE.FEATURE_10,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_0,
               FEATURE.FEATURE_24,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_39],
  'id': 69,
  'movement': MOVEMENT.MOVEMENT_10,
  'size': SIZE.SIZE_2,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_17,
  'features': [FEATURE.FEATURE_4,
               FEATURE.FEATURE_26,
               FEATURE.FEATURE_25,
               FEATURE.FEATURE_41,
               FEATURE.FEATURE_17,
               FEATURE.FEATURE_2],
  'id': 19,
  'movement': MOVEMENT.MOVEMENT_6,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_15,
  'features': [FEATURE.FEATURE_4,
               FEATURE.FEATURE_17,
               FEATURE.FEATURE_25,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_36,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_41],
  'id': 17,
  'movement': MOVEMENT.MOVEMENT_10,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_18,
  'features': [FEATURE.FEATURE_4,
               FEATURE.FEATURE_17,
               FEATURE.FEATURE_27,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_45,
               FEATURE.FEATURE_46],
  'id': 137,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_18,
  'features': [FEATURE.FEATURE_8,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_24,
               FEATURE.FEATURE_0],
  'id': 56,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_8,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_18,
  'features': [FEATURE.FEATURE_9,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_24,
               FEATURE.FEATURE_2],
  'id': 136,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_15,
  'features': [FEATURE.FEATURE_4,
               FEATURE.FEATURE_17,
               FEATURE.FEATURE_25,
               FEATURE.FEATURE_29],
  'id': 23,
  'movement': MOVEMENT.MOVEMENT_10,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_3,
  'features': [FEATURE.FEATURE_41,
               FEATURE.FEATURE_27,
               FEATURE.FEATURE_12,
               FEATURE.FEATURE_46],
  'id': 20,
  'movement': MOVEMENT.MOVEMENT_10,
  'size': SIZE.SIZE_1,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_18,
  'features': [FEATURE.FEATURE_24,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_8,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_44],
  'id': 193,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_1,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_3,
  'features': [FEATURE.FEATURE_17,
               FEATURE.FEATURE_25,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_4,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_3],
  'id': 25,
  'movement': MOVEMENT.MOVEMENT_10,
  'size': SIZE.SIZE_1,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_0,
               FEATURE.FEATURE_3,
               FEATURE.FEATURE_18,
               FEATURE.FEATURE_38,
               FEATURE.FEATURE_15,
               FEATURE.FEATURE_28],
  'id': 164,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_0,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_17,
  'features': [FEATURE.FEATURE_0,
               FEATURE.FEATURE_6,
               FEATURE.FEATURE_41,
               FEATURE.FEATURE_48,
               FEATURE.FEATURE_49,
               FEATURE.FEATURE_51,
               FEATURE.FEATURE_45],
  'id': 134,
  'movement': MOVEMENT.MOVEMENT_1,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_16,
  'features': [FEATURE.FEATURE_39,
               FEATURE.FEATURE_6,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_52,
               FEATURE.FEATURE_46],
  'id': 124,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_6,
  'features': [FEATURE.FEATURE_11,
               FEATURE.FEATURE_10,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_35,
               FEATURE.FEATURE_52,
               FEATURE.FEATURE_46],
  'id': 1,
  'movement': MOVEMENT.MOVEMENT_5,
  'size': SIZE.SIZE_10,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_21},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_19,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_47,
               FEATURE.FEATURE_12,
               FEATURE.FEATURE_15],
  'id': 76,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_21,
               FEATURE.FEATURE_47,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_27,
               FEATURE.FEATURE_45,
               FEATURE.FEATURE_42],
  'id': 95,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_6,
  'features': [FEATURE.FEATURE_21,
               FEATURE.FEATURE_18,
               FEATURE.FEATURE_19,
               FEATURE.FEATURE_49,
               FEATURE.FEATURE_52,
               FEATURE.FEATURE_10,
               FEATURE.FEATURE_11],
  'id': 121,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_13,
  'features': [FEATURE.FEATURE_22,
               FEATURE.FEATURE_2,
               FEATURE.FEATURE_9,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_17],
  'id': 18,
  'movement': MOVEMENT.MOVEMENT_7,
  'size': SIZE.SIZE_10,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_10,
  'features': [FEATURE.FEATURE_50,
               FEATURE.FEATURE_49,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_10,
               FEATURE.FEATURE_45],
  'id': 98,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_11,
  'features': [FEATURE.FEATURE_31],
  'id': 139,
  'movement': MOVEMENT.MOVEMENT_1,
  'size': SIZE.SIZE_0,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_10},
 {'body': BODY.BODY_6,
  'features': [FEATURE.FEATURE_10,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_47,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_45,
               FEATURE.FEATURE_49,
               FEATURE.FEATURE_19],
  'id': 73,
  'movement': MOVEMENT.MOVEMENT_5,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_21,
               FEATURE.FEATURE_15,
               FEATURE.FEATURE_45,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_4],
  'id': 74,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_7,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_17,
  'features': [FEATURE.FEATURE_45,
               FEATURE.FEATURE_10,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_0],
  'id': 97,
  'movement': MOVEMENT.MOVEMENT_7,
  'size': SIZE.SIZE_5,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_7,
  'features': [FEATURE.FEATURE_50,
               FEATURE.FEATURE_7,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_44],
  'id': 13,
  'movement': MOVEMENT.MOVEMENT_3,
  'size': SIZE.SIZE_8,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_20},
 {'body': BODY.BODY_5,
  'features': [FEATURE.FEATURE_50,
               FEATURE.FEATURE_49,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_45,
               FEATURE.FEATURE_21,
               FEATURE.FEATURE_8,
               FEATURE.FEATURE_11],
  'id': 85,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_10,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_19,
               FEATURE.FEATURE_16,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_27,
               FEATURE.FEATURE_47,
               FEATURE.FEATURE_12,
               FEATURE.FEATURE_20],
  'id': 86,
  'movement': MOVEMENT.MOVEMENT_2,
  'size': SIZE.SIZE_11,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_6,
  'features': [FEATURE.FEATURE_47,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_51,
               FEATURE.FEATURE_50,
               FEATURE.FEATURE_10,
               FEATURE.FEATURE_11],
  'id': 87,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_3,
  'features': [FEATURE.FEATURE_10,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_40,
               FEATURE.FEATURE_45,
               FEATURE.FEATURE_46,
               FEATURE.FEATURE_29],
  'id': 195,
  'movement': MOVEMENT.MOVEMENT_10,
  'size': SIZE.SIZE_1,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_1,
  'features': [FEATURE.FEATURE_24,
               FEATURE.FEATURE_15,
               FEATURE.FEATURE_47,
               FEATURE.FEATURE_6,
               FEATURE.FEATURE_11],
  'id': 118,
  'movement': MOVEMENT.MOVEMENT_1,
  'size': SIZE.SIZE_4,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_12,
  'features': [FEATURE.FEATURE_50,
               FEATURE.FEATURE_49,
               FEATURE.FEATURE_0,
               FEATURE.FEATURE_10,
               FEATURE.FEATURE_11],
  'id': 5,
  'movement': MOVEMENT.MOVEMENT_3,
  'size': SIZE.SIZE_6,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_12,
  'features': [FEATURE.FEATURE_0,
               FEATURE.FEATURE_27,
               FEATURE.FEATURE_25,
               FEATURE.FEATURE_20,
               FEATURE.FEATURE_45,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_12,
               FEATURE.FEATURE_17],
  'id': 119,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_10,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_11},
 {'body': BODY.BODY_3,
  'features': [FEATURE.FEATURE_0,
               FEATURE.FEATURE_41,
               FEATURE.FEATURE_24,
               FEATURE.FEATURE_39,
               FEATURE.FEATURE_10,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_46],
  'id': 157,
  'movement': MOVEMENT.MOVEMENT_10,
  'size': SIZE.SIZE_2,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_12,
  'features': [FEATURE.FEATURE_50,
               FEATURE.FEATURE_17,
               FEATURE.FEATURE_0,
               FEATURE.FEATURE_45,
               FEATURE.FEATURE_41,
               FEATURE.FEATURE_20],
  'id': 26,
  'movement': MOVEMENT.MOVEMENT_1,
  'size': SIZE.SIZE_9,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_17,
  'features': [FEATURE.FEATURE_27,
               FEATURE.FEATURE_28,
               FEATURE.FEATURE_29,
               FEATURE.FEATURE_0,
               FEATURE.FEATURE_3,
               FEATURE.FEATURE_45],
  'id': 168,
  'movement': MOVEMENT.MOVEMENT_5,
  'size': SIZE.SIZE_9,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9},
 {'body': BODY.BODY_16,
  'features': [FEATURE.FEATURE_0,
               FEATURE.FEATURE_9,
               FEATURE.FEATURE_11,
               FEATURE.FEATURE_17,
               FEATURE.FEATURE_45,
               FEATURE.FEATURE_52,
               FEATURE.FEATURE_51],
  'id': 126,
  'movement': MOVEMENT.MOVEMENT_4,
  'size': SIZE.SIZE_5,
  'structure': STRUCTURE.STRUCTURE_5,
  'weapon': STANDARD_WEAPON.WEAPON_9}]


class MATERIAL(DjangoEnum):
    records = (('UNKNOWN', 0, 'неизвестен'),
               ('MATERIAL_1', 1, 'кость'),
               ('MATERIAL_2', 2, 'металл'),
               ('MATERIAL_3', 3, 'дерево'),
               ('MATERIAL_4', 4, 'камень'),
               ('MATERIAL_5', 5, 'хитин'),
               ('MATERIAL_6', 6, 'кристалл'),
               ('MATERIAL_7', 7, 'экзотика'),
               ('MATERIAL_8', 8, 'ороговевшая кожа'),
               ('MATERIAL_9', 9, 'зуб'),
               ('MATERIAL_10', 10, 'кожа'))


MATERIALS = {STANDARD_WEAPON.WEAPON_0: MATERIAL.MATERIAL_3,
             STANDARD_WEAPON.WEAPON_1: MATERIAL.MATERIAL_3,
             STANDARD_WEAPON.WEAPON_2: MATERIAL.MATERIAL_5,
             STANDARD_WEAPON.WEAPON_3: MATERIAL.MATERIAL_5,
             STANDARD_WEAPON.WEAPON_4: MATERIAL.MATERIAL_7,
             STANDARD_WEAPON.WEAPON_5: MATERIAL.MATERIAL_2,
             STANDARD_WEAPON.WEAPON_6: MATERIAL.MATERIAL_2,
             STANDARD_WEAPON.WEAPON_7: MATERIAL.MATERIAL_2,
             STANDARD_WEAPON.WEAPON_8: MATERIAL.MATERIAL_5,
             STANDARD_WEAPON.WEAPON_9: MATERIAL.MATERIAL_9,
             STANDARD_WEAPON.WEAPON_10: MATERIAL.MATERIAL_8,
             STANDARD_WEAPON.WEAPON_11: MATERIAL.MATERIAL_8,
             STANDARD_WEAPON.WEAPON_12: MATERIAL.MATERIAL_2,
             STANDARD_WEAPON.WEAPON_13: MATERIAL.MATERIAL_7,
             STANDARD_WEAPON.WEAPON_14: MATERIAL.MATERIAL_2,
             STANDARD_WEAPON.WEAPON_15: MATERIAL.MATERIAL_2,
             STANDARD_WEAPON.WEAPON_16: MATERIAL.MATERIAL_3,
             STANDARD_WEAPON.WEAPON_17: MATERIAL.MATERIAL_2,
             STANDARD_WEAPON.WEAPON_18: MATERIAL.MATERIAL_10,
             STANDARD_WEAPON.WEAPON_19: MATERIAL.MATERIAL_3,
             STANDARD_WEAPON.WEAPON_20: MATERIAL.MATERIAL_8,
             STANDARD_WEAPON.WEAPON_21: MATERIAL.MATERIAL_8,
             STANDARD_WEAPON.WEAPON_22: MATERIAL.MATERIAL_2,
             STANDARD_WEAPON.WEAPON_23: MATERIAL.MATERIAL_2,
             STANDARD_WEAPON.WEAPON_24: MATERIAL.MATERIAL_2,
             STANDARD_WEAPON.WEAPON_25: MATERIAL.MATERIAL_7,
             STANDARD_WEAPON.WEAPON_26: MATERIAL.MATERIAL_7}


class Command(BaseCommand):

    help = 'fill new mobs properties'

    def handle(self,  *args,  **options):

        mobs = {mob['id']: mob for mob in MOBS}

        for mob in models.MobRecord.objects.all().order_by('id').iterator():
            print('process mob {}'.format(mob.id))

            if mob.id not in mobs:
                continue

            new_data = mobs[mob.id]

            data = s11n.from_json(mob.data)

            data['structure'] = new_data['structure'].value
            data['features'] = [feature.value for feature in new_data['features']]
            data['movement'] = new_data['movement'].value
            data['body'] = new_data['body'].value
            data['size'] = new_data['size'].value
            data['weapons'] = [{'weapon': new_data['weapon'].value,
                                'material': MATERIALS[new_data['weapon']].value,
                                'power_type': 2}]

            mob.data = s11n.to_json(data)

            mob.save()
