# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='data',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='data',
            field=models.TextField(default='{}'),
        ),
    ]
