# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-23 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20161019_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='account',
        ),
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='lot',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
    ]
