---
- name: pip | packages installed
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - virtualenv
    - docker-py

- name: app | deps installed
  pip:
    requirements: "{{ repo_dir }}/requirements.txt"
    virtualenv: "{{ venv_dir }}"
    state: present

- name: app | settings file created
  copy:
    src: "{{ app_dir }}/settings_local_example.py"
    dest: "{{ app_dir }}/settings_local.py"

- name: app | settings file configured
  replace:
    dest: "{{ app_dir }}/settings_local.py"
    regexp: <USERNAME>
    replace: "{{ ansible_user_id }}"
