# Generated by Django 2.2.8 on 2020-05-11 13:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_data_protector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('core_id', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deletion_history',
            },
        ),
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('core_id', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=32)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deletion_requests',
            },
        ),
    ]
