# Generated by Django 3.1.13 on 2021-11-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_data_protector', '0002_deletionhistory_deletionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletionrequest',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='subreport',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
