# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='version',
            field=models.BigIntegerField(default=0),
        ),
    ]
