# Generated by Django 3.1.13 on 2021-11-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_diary', '0003_auto_20211017_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
