# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 16:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20150506_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turn_number', models.BigIntegerField(db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='mapinfo',
            name='cells',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mapinfo',
            name='statistics',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='mapinfo',
            name='terrain',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='worldinfo',
            name='data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
