# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20161019_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapregion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mapregion',
            name='turn_number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterIndexTogether(
            name='mapregion',
            index_together=set([('turn_number', 'created_at')]),
        ),
    ]
