# Generated by Django 3.1.13 on 2021-11-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20161019_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapregion',
            name='data',
            field=models.JSONField(),
        ),
    ]
