# Generated by Django 2.2.8 on 2020-05-04 14:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discord_id', models.BigIntegerField(null=True, unique=True)),
                ('game_id', models.BigIntegerField(null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='BindCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expire_at', models.DateTimeField(db_index=True)),
                ('account', models.OneToOneField(db_column='account', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tt_discord.Account')),
            ],
            options={
                'db_table': 'bind_codes',
            },
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(db_index=True, null=True)),
                ('account', models.ForeignKey(db_column='account', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tt_discord.Account')),
            ],
            options={
                'db_table': 'game_data',
                'unique_together': {('account', 'type')},
                'index_together': {('updated_at', 'synced_at')},
            },
        ),
    ]
