# Generated by Django 3.2.9 on 2021-11-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_discord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
