# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-15 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='selllot',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
