# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-18 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellLot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=32)),
                ('item', models.UUIDField(unique=True)),
                ('price', models.IntegerField()),
                ('owner', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sell_lots',
            },
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
        migrations.AddField(
            model_name='logrecord',
            name='owner',
            field=models.BigIntegerField(null=True),
        ),
    ]
