# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-18 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_market', '0003_logrecord_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
