# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-26 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_market', '0004_auto_20170918_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selllot',
            name='id',
        ),
        migrations.AlterField(
            model_name='selllot',
            name='item',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
