# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-11-23 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_tag_meta_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='meta_type',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
