# Generated by Django 2.1.15 on 2019-12-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20191123_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='default',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
