# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import rels.django


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_add_none_specialilization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
        migrations.RemoveField(
            model_name='place',
            name='expected_size',
        ),
        migrations.RemoveField(
            model_name='place',
            name='freedom',
        ),
        migrations.RemoveField(
            model_name='place',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='place',
            name='keepers_goods',
        ),
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.RemoveField(
            model_name='place',
            name='production',
        ),
        migrations.RemoveField(
            model_name='place',
            name='safety',
        ),
        migrations.RemoveField(
            model_name='place',
            name='size',
        ),
        migrations.RemoveField(
            model_name='place',
            name='stability',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='place',
            name='transport',
        ),
        migrations.AddField(
            model_name='place',
            name='power',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='place',
            name='modifier',
            field=rels.django.RelationIntegerField(default=9),
        ),
    ]
