# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_add_power_to_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='heroes_number',
        ),
        migrations.RemoveField(
            model_name='place',
            name='power',
        ),
    ]
