# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-05-08 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20160424_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='integrity',
        ),
    ]
