# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-02 15:17
from __future__ import unicode_literals

from django.db import migrations


def migrate_artifacts(apps, schema_editor):
    apps.get_model("artifacts", "ArtifactRecord").objects.filter(epic_effect=1006).update(epic_effect=1015)
    apps.get_model("artifacts", "ArtifactRecord").objects.filter(epic_effect=1014).update(epic_effect=1015)


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_auto_20161019_1613'),
    ]

    operations = [
        migrations.RunPython(
            migrate_artifacts,
        ),
    ]
